#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.Design;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Routing;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
    using LCore.Extensions;
    
    #line default
    #line hidden
    using LMVC;
    using LMVC.Account;
    using LMVC.Annotations;
    using LMVC.Context;
    using LMVC.Controllers;
    using LMVC.Extensions;
    using LMVC.Models;
    using LMVC.Routes;
    using Singularity;
    
    #line 5 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
    using Singularity.Extensions;
    
    #line default
    #line hidden
    using Singularity.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CustomExport/Fields/ExportType_After.cshtml")]
    public partial class _Views_CustomExport_Fields_ExportType_After_cshtml : System.Web.Mvc.WebViewPage<IViewField>
    {
        public _Views_CustomExport_Fields_ExportType_After_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n\r\n");

WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
  
    var Export = (CustomExport)Model.ModelData;

    Type ModelExportType = null;

    if (Export.ExportType != null)
        {
            ModelExportType = L.Ref.FindType(Export.ExportType);
        }

    var BasedMeta = new Dictionary<string, List<ModelMetadata>>();

    Dictionary<string, ModelMetadata> AllMeta = ModelExportType == null ?
        new Dictionary<string, ModelMetadata>() :
        ModelExportType.GetMeta();

    AllMeta.Keys.Each(Meta =>
    {
        string BaseKey = "";

        if (Meta.Contains("."))
            {
            BaseKey = Meta.Substring(0, Meta.LastIndexOf('.'));
            }

        if (!BasedMeta.ContainsKey(BaseKey))
            {
            BasedMeta[BaseKey] = new List<ModelMetadata>();
            }

        BasedMeta[BaseKey].Add(AllMeta[Meta]);
    });

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 43 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
 if (!Model.ViewTypes.HasAny(ControllerHelper.ViewType.TableCell))
    {
    if (ModelExportType != null)
        {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"field-list-add\"");

WriteLiteral(" target=\"#Fields\"");

WriteLiteral(" position=\"end\"");

WriteLiteral(">\r\n            <h3>");

            
            #line 48 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
           Write(Html.TextContent("Singularity_CustomExport_Fields", "Fields"));

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n\r\n");

            
            #line 50 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
            
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
             foreach (string BaseKey in BasedMeta.Keys)
                {

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteLiteral(" class=\"btn-info btn left method-show-hide\"");

WriteAttribute("click-fade-toggle", Tuple.Create(" click-fade-toggle=\"", 1380), Tuple.Create("\"", 1441)
, Tuple.Create(Tuple.Create("", 1400), Tuple.Create(".field-group-", 1400), true)
            
            #line 52 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
                 , Tuple.Create(Tuple.Create("", 1413), Tuple.Create<System.Object, System.Int32>(BaseKey.ReplaceAll(".", "")
            
            #line default
            #line hidden
, 1413), false)
);

WriteLiteral(">\r\n                    <glyph");

WriteAttribute("class", Tuple.Create(" class=\"", 1471), Tuple.Create("\"", 1519)
, Tuple.Create(Tuple.Create("", 1479), Tuple.Create("field-group-", 1479), true)
            
            #line 53 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
, Tuple.Create(Tuple.Create("", 1491), Tuple.Create<System.Object, System.Int32>(BaseKey.ReplaceAll(".", "")
            
            #line default
            #line hidden
, 1491), false)
);

WriteLiteral(">&#x2b;</glyph>\r\n                    <glyph");

WriteAttribute("class", Tuple.Create(" class=\"", 1563), Tuple.Create("\"", 1611)
, Tuple.Create(Tuple.Create("", 1571), Tuple.Create("field-group-", 1571), true)
            
            #line 54 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
, Tuple.Create(Tuple.Create("", 1583), Tuple.Create<System.Object, System.Int32>(BaseKey.ReplaceAll(".", "")
            
            #line default
            #line hidden
, 1583), false)
);

WriteLiteral(" style=\" display: none;\"");

WriteLiteral(">&#x2212;</glyph>\r\n                </span>\r\n");

            
            #line 56 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"

                if (string.IsNullOrEmpty(BaseKey))
                    {

            
            #line default
            #line hidden
WriteLiteral("                    <h4>");

            
            #line 59 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
                   Write(ModelExportType.GetFriendlyTypeName());

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n");

            
            #line 60 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
                    continue;
                    }

            
            #line default
            #line hidden
WriteLiteral("                <h4>");

            
            #line 62 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
               Write(BaseKey.ReplaceAll(".", " "));

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n");

            
            #line 63 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"

                if (BasedMeta.ContainsKey(BaseKey))
                    {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 2038), Tuple.Create("\"", 2086)
, Tuple.Create(Tuple.Create("", 2046), Tuple.Create("field-group-", 2046), true)
            
            #line 66 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
, Tuple.Create(Tuple.Create("", 2058), Tuple.Create<System.Object, System.Int32>(BaseKey.ReplaceAll(".", "")
            
            #line default
            #line hidden
, 2058), false)
);

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">\r\n");

            
            #line 67 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
                         foreach (var Meta in BasedMeta[BaseKey])
                            {
                            string Key = Meta.PropertyName;

                            if (!string.IsNullOrEmpty(BaseKey))
                                {
                                Key = $"{BaseKey}.{Key}";
                                }


            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"field-list-row\"");

WriteLiteral(" data-field-name=\"");

            
            #line 76 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
                                                                    Write(Key);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("title", Tuple.Create(" title=\"", 2547), Tuple.Create("\"", 2559)
            
            #line 76 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
      , Tuple.Create(Tuple.Create("", 2555), Tuple.Create<System.Object, System.Int32>(Key
            
            #line default
            #line hidden
, 2555), false)
);

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"add-button\"");

WriteLiteral(">\r\n                                    <glyph>&#x2b;</glyph>\r\n                   " +
"             </div>\r\n                                <div");

WriteLiteral(" class=\"field-name\"");

WriteLiteral(">\r\n");

WriteLiteral("                                    ");

            
            #line 81 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
                               Write(Meta.GetDisplayName().Humanize());

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n");

            
            #line 84 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n");

            
            #line 86 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n");

            
            #line 89 "..\..\Views\CustomExport\Fields\ExportType_After.cshtml"
        }
    }
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
