#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    
    #line 8 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 10 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
    using System.ComponentModel;
    
    #line default
    #line hidden
    
    #line 16 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 17 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
    using System.ComponentModel.DataAnnotations.Schema;
    
    #line default
    #line hidden
    
    #line 11 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
    using System.ComponentModel.Design;
    
    #line default
    #line hidden
    using System.IO;
    
    #line 14 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 15 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
    using System.Linq.Expressions;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    
    #line 12 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
    using System.Web;
    
    #line default
    #line hidden
    using System.Web.Helpers;
    
    #line 13 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
    using LCore;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
    using Singularity;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
    using Singularity.Context;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
    using Singularity.Controllers;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
    using Singularity.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Fields/Edit/Boolean.cshtml")]
    public partial class _Views_Shared_Fields_Edit_Boolean_cshtml : System.Web.Mvc.WebViewPage<IViewField>
    {
        public _Views_Shared_Fields_Edit_Boolean_cshtml()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n\r\n");
















WriteLiteral("\r\n");


            
            #line 19 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
  
    Boolean Check = (Model.PropertyData is Boolean && (Boolean)Model.PropertyData == true) ||
        (Model.PropertyData is Boolean? && (Boolean?)Model.PropertyData == (Boolean?)true);


            
            #line default
            #line hidden
WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n<input type=\"radio\"\r\n       id=\"");


            
            #line 28 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
      Write(Model.Meta.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n       name=\"");


            
            #line 29 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
        Write(Model.Meta.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n       checked=\"");


            
            #line 30 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
            Write(Check == false);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n       value=\"false\" />\r\n<span>No</span>\r\n<input type=\"radio\"\r\n       id=\"");


            
            #line 34 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
      Write(Model.Meta.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n       name=\"");


            
            #line 35 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
        Write(Model.Meta.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n       checked=\"");


            
            #line 36 "..\..\Views\Shared\Fields\Edit\Boolean.cshtml"
            Write(Check == true);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n       value=\"true\" />\r\n<span>Yes</span>");


        }
    }
}
#pragma warning restore 1591
