#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.Design;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Routing;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LCore.Extensions;
    using Singularity;
    
    #line 3 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
    using Singularity.Annotations;
    
    #line default
    #line hidden
    using Singularity.Context;
    using Singularity.Controllers;
    
    #line 2 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
    using Singularity.Extensions;
    
    #line default
    #line hidden
    using Singularity.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Fields/Edit/Dropdown.cshtml")]
    public partial class _Views_Shared_Fields_Edit_Dropdown_cshtml : System.Web.Mvc.WebViewPage<IViewField>
    {
        public _Views_Shared_Fields_Edit_Dropdown_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
  
    FieldType_Dropdown FieldAttr = Model.Meta.GetAttribute<FieldType_Dropdown>();

    bool Required = Model.Meta.IsRequired;

    string EmptyValue = FieldAttr.EmptyValue;
    string EmptyKey = FieldAttr.EmptyKey;

    List<SelectListItem> Items = FieldAttr.KeyValues(ViewContext).Select(KeyValue => new SelectListItem
        {
        Text = KeyValue.Key,
        Value = KeyValue.Value,
        Selected = (Model.PropertyData ?? "").ToString() == KeyValue.Value
        }).ToList();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 23 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
 if (FieldAttr.MultiSelect)
    {

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"option-checks\"");

WriteLiteral(">\r\n\r\n        <input");

WriteAttribute("name", Tuple.Create(" name=\"", 708), Tuple.Create("\"", 739)
            
            #line 27 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 715), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 715), false)
);

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" />\r\n\r\n");

            
            #line 29 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
        
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
         foreach (SelectListItem i in Items)
            {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"list-check\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"checkbox\"");

WriteAttribute("id", Tuple.Create("\r\n                       id=\"", 907), Tuple.Create("\"", 973)
            
            #line 33 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 936), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 936), false)
, Tuple.Create(Tuple.Create("", 962), Tuple.Create("_", 962), true)
            
            #line 33 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 963), Tuple.Create<System.Object, System.Int32>(i.Value
            
            #line default
            #line hidden
, 963), false)
);

WriteAttribute("name", Tuple.Create("\r\n                       name=\"", 974), Tuple.Create("\"", 1029)
            
            #line 34 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 1005), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 1005), false)
);

WriteAttribute("value", Tuple.Create("\r\n                       value=\"", 1030), Tuple.Create("\"", 1070)
            
            #line 35 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 1062), Tuple.Create<System.Object, System.Int32>(i.Value
            
            #line default
            #line hidden
, 1062), false)
);

WriteLiteral("\r\n                       ");

            
            #line 36 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
                   Write((Model.PropertyData ?? "").ToString().Contains(i.Value) ? Html.Raw("checked=\"true\"") : Html.Raw(""));

            
            #line default
            #line hidden
WriteLiteral(">\r\n                <label");

WriteAttribute("for", Tuple.Create(" for=\"", 1225), Tuple.Create("\"", 1268)
            
            #line 37 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 1231), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 1231), false)
, Tuple.Create(Tuple.Create("", 1257), Tuple.Create("_", 1257), true)
            
            #line 37 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 1258), Tuple.Create<System.Object, System.Int32>(i.Value
            
            #line default
            #line hidden
, 1258), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 38 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
               Write(i.Text);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </label>\r\n            </div>\r\n");

            
            #line 41 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 43 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
    }
else
    {

            
            #line default
            #line hidden
WriteLiteral("    <select");

WriteAttribute("name", Tuple.Create(" name=\"", 1405), Tuple.Create("\"", 1436)
            
            #line 46 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 1412), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 1412), false)
);

WriteAttribute("id", Tuple.Create(" id=\"", 1437), Tuple.Create("\"", 1466)
            
            #line 46 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 1442), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 1442), false)
);

WriteLiteral(">\r\n");

            
            #line 47 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
        
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
         if (!Required)
            {

            
            #line default
            #line hidden
WriteLiteral("            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 1529), Tuple.Create("\"", 1548)
            
            #line 49 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 1537), Tuple.Create<System.Object, System.Int32>(EmptyValue
            
            #line default
            #line hidden
, 1537), false)
);

WriteLiteral(" ");

            
            #line 49 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
                                    Write((string)Model.PropertyData == EmptyValue ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 50 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
           Write(EmptyKey);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </option>\r\n");

            
            #line 52 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"

            }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 54 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
         foreach (SelectListItem Item in Items)
            {

            
            #line default
            #line hidden
WriteLiteral("            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 1764), Tuple.Create("\"", 1783)
            
            #line 56 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 1772), Tuple.Create<System.Object, System.Int32>(Item.Value
            
            #line default
            #line hidden
, 1772), false)
);

WriteLiteral(" ");

            
            #line 56 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
                                    Write(Item.Selected ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 57 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
           Write(Item.Text);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </option>\r\n");

            
            #line 59 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("    </select>\r\n");

            
            #line 61 "..\..\Views\Shared\Fields\Edit\Dropdown.cshtml"
    }
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
