#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.Design;
    using System.IO;
    
    #line 3 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Routing;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
    using LCore.Extensions;
    
    #line default
    #line hidden
    using Singularity;
    using Singularity.Context;
    using Singularity.Controllers;
    
    #line 2 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
    using Singularity.Extensions;
    
    #line default
    #line hidden
    using Singularity.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Fields/Edit/Enum.cshtml")]
    public partial class _Views_Shared_Fields_Edit_Enum_cshtml : System.Web.Mvc.WebViewPage<IViewField>
    {
        public _Views_Shared_Fields_Edit_Enum_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
  
    Type EnumType = Model.Meta.ModelType.IsEnum ? Model.Meta.ModelType : Model.Meta.ModelType.GetGenericArguments()[0];

    Array Values = Enum.GetValues(EnumType);

    IEnumerable<Enum> Enums = Values.Cast<Enum>();


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 17 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
 if (EnumType.HasAttribute<FlagsAttribute>())
    {

            
            #line default
            #line hidden
WriteLiteral("    <span");

WriteLiteral(" class=\"enum-checks\"");

WriteLiteral(">\r\n\r\n        <input");

WriteAttribute("name", Tuple.Create(" name=\"", 464), Tuple.Create("\"", 495)
            
            #line 21 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 471), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 471), false)
);

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" />\r\n\r\n");

            
            #line 23 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
        
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
         foreach (Enum e in Enums)
            {

            
            #line default
            #line hidden
WriteLiteral("            <span");

WriteLiteral(" class=\"enum-check\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"checkbox\"");

WriteAttribute("id", Tuple.Create("\r\n                       id=\"", 654), Tuple.Create("\"", 725)
            
            #line 27 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 683), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 683), false)
, Tuple.Create(Tuple.Create("", 709), Tuple.Create("_", 709), true)
            
            #line 27 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 710), Tuple.Create<System.Object, System.Int32>(e.ToString()
            
            #line default
            #line hidden
, 710), false)
);

WriteAttribute("name", Tuple.Create("\r\n                       name=\"", 726), Tuple.Create("\"", 781)
            
            #line 28 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 757), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 757), false)
);

WriteAttribute("value", Tuple.Create("\r\n                       value=\"", 782), Tuple.Create("\"", 827)
            
            #line 29 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 814), Tuple.Create<System.Object, System.Int32>(e.ToString()
            
            #line default
            #line hidden
, 814), false)
);

WriteLiteral("\r\n                       ");

            
            #line 30 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
                   Write((Model.PropertyData ?? "").ToString().Contains(e.ToString()) ? Html.Raw("checked=\"true\"") : Html.Raw(""));

            
            #line default
            #line hidden
WriteLiteral(">\r\n                <label");

WriteAttribute("for", Tuple.Create(" for=\"", 987), Tuple.Create("\"", 1035)
            
            #line 31 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 993), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 993), false)
, Tuple.Create(Tuple.Create("", 1019), Tuple.Create("_", 1019), true)
            
            #line 31 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 1020), Tuple.Create<System.Object, System.Int32>(e.ToString()
            
            #line default
            #line hidden
, 1020), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 32 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
               Write(e.GetFriendlyName());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </label>\r\n            </span>\r\n");

            
            #line 35 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("    </span>\r\n");

            
            #line 37 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
    }
else
    {
    List<SelectListItem> Items = Enums.Select(e => new SelectListItem
        {
        Text = e.GetFriendlyName(),
        Value = e.ToString(),
        Selected = (Model.PropertyData ?? "").ToString() == e.ToString()
        }).ToList();

    Items.Sort((Func<SelectListItem, IComparable>
        )(i => (IComparable)i.Text));


            
            #line default
            #line hidden
WriteLiteral("    <select");

WriteAttribute("name", Tuple.Create(" name=\"", 1527), Tuple.Create("\"", 1558)
            
            #line 50 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 1534), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 1534), false)
);

WriteAttribute("id", Tuple.Create(" id=\"", 1559), Tuple.Create("\"", 1588)
            
            #line 50 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 1564), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 1564), false)
);

WriteLiteral(">\r\n");

            
            #line 51 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
        
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
         foreach (SelectListItem Item in Items)
            {

            
            #line default
            #line hidden
WriteLiteral("            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 1675), Tuple.Create("\"", 1694)
            
            #line 53 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 1683), Tuple.Create<System.Object, System.Int32>(Item.Value
            
            #line default
            #line hidden
, 1683), false)
);

WriteAttribute("selected", Tuple.Create(" selected=\"", 1695), Tuple.Create("\"", 1720)
            
            #line 53 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 1706), Tuple.Create<System.Object, System.Int32>(Item.Selected
            
            #line default
            #line hidden
, 1706), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 54 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
           Write(Item.Text);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </option>\r\n");

            
            #line 56 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("    </select>\r\n");

            
            #line 58 "..\..\Views\Shared\Fields\Edit\Enum.cshtml"
    /*
                @Html.DropDownList(Model.Meta.PropertyName, Items, new { @class = "select-list" })
                */
    }

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
