#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    
    #line 8 "..\..\Views\Shared\Fields\Edit\Hidden.cshtml"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Views\Shared\Fields\Edit\Hidden.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 10 "..\..\Views\Shared\Fields\Edit\Hidden.cshtml"
    using System.ComponentModel;
    
    #line default
    #line hidden
    
    #line 16 "..\..\Views\Shared\Fields\Edit\Hidden.cshtml"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 17 "..\..\Views\Shared\Fields\Edit\Hidden.cshtml"
    using System.ComponentModel.DataAnnotations.Schema;
    
    #line default
    #line hidden
    
    #line 11 "..\..\Views\Shared\Fields\Edit\Hidden.cshtml"
    using System.ComponentModel.Design;
    
    #line default
    #line hidden
    using System.IO;
    
    #line 14 "..\..\Views\Shared\Fields\Edit\Hidden.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 15 "..\..\Views\Shared\Fields\Edit\Hidden.cshtml"
    using System.Linq.Expressions;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    
    #line 12 "..\..\Views\Shared\Fields\Edit\Hidden.cshtml"
    using System.Web;
    
    #line default
    #line hidden
    using System.Web.Helpers;
    
    #line 13 "..\..\Views\Shared\Fields\Edit\Hidden.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Routing;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LCore;
    
    #line 4 "..\..\Views\Shared\Fields\Edit\Hidden.cshtml"
    using Singularity;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Shared\Fields\Edit\Hidden.cshtml"
    using Singularity.Context;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\Shared\Fields\Edit\Hidden.cshtml"
    using Singularity.Controllers;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Shared\Fields\Edit\Hidden.cshtml"
    using Singularity.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Fields/Edit/Hidden.cshtml")]
    public partial class _Views_Shared_Fields_Edit_Hidden_cshtml : System.Web.Mvc.WebViewPage<IViewField>
    {
        public _Views_Shared_Fields_Edit_Hidden_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n\r\n");

WriteLiteral("\r\n");

            
            #line 19 "..\..\Views\Shared\Fields\Edit\Hidden.cshtml"
  

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("<input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("id", Tuple.Create("\r\n       id=\"", 525), Tuple.Create("\"", 562)
            
            #line 25 "..\..\Views\Shared\Fields\Edit\Hidden.cshtml"
, Tuple.Create(Tuple.Create("", 538), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 538), false)
);

WriteAttribute("name", Tuple.Create("\r\n       name=\"", 563), Tuple.Create("\"", 602)
            
            #line 26 "..\..\Views\Shared\Fields\Edit\Hidden.cshtml"
, Tuple.Create(Tuple.Create("", 578), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 578), false)
);

WriteAttribute("value", Tuple.Create("\r\n       value=\"", 603), Tuple.Create("\"", 659)
            
            #line 27 "..\..\Views\Shared\Fields\Edit\Hidden.cshtml"
, Tuple.Create(Tuple.Create("", 619), Tuple.Create<System.Object, System.Int32>((Model.PropertyData ?? "").ToString()
            
            #line default
            #line hidden
, 619), false)
);

WriteLiteral(" />");

        }
    }
}
#pragma warning restore 1591
