#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.Design;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Routing;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LCore.Extensions;
    using LMVC;
    using LMVC.Account;
    using LMVC.Annotations;
    using LMVC.Context;
    using LMVC.Controllers;
    using LMVC.Extensions;
    using LMVC.Models;
    using Singularity;
    
    #line 2 "..\..\Views\Shared\Manage\Fields\FieldHeader.cshtml"
    using Singularity.Extensions;
    
    #line default
    #line hidden
    using Singularity.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Manage/Fields/FieldHeader.cshtml")]
    public partial class _Views_Shared_Manage_Fields_FieldHeader_cshtml : System.Web.Mvc.WebViewPage<IViewField>
    {
        public _Views_Shared_Manage_Fields_FieldHeader_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Shared\Manage\Fields\FieldHeader.cshtml"
  
    var Attr = Model.Meta.GetAttribute<FieldHeaderAttribute>();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

            
            #line 11 "..\..\Views\Shared\Manage\Fields\FieldHeader.cshtml"
Write(Html.Raw($"<h{Attr.HeaderType}>"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 12 "..\..\Views\Shared\Manage\Fields\FieldHeader.cshtml"
Write(Html.TextContent($"Manage_{(ViewBag.Create == true ? "Create" : "Edit")}_Field_Header_{Model.ModelData.GetFriendlyTypeName()}_{Attr.HeaderTitle}", Attr.HeaderTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 13 "..\..\Views\Shared\Manage\Fields\FieldHeader.cshtml"
Write(Html.Raw($"</h{Attr.HeaderType}>"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 15 "..\..\Views\Shared\Manage\Fields\FieldHeader.cshtml"
 if (Attr.HorizontalRule)
    {

            
            #line default
            #line hidden
WriteLiteral("    <hr />\r\n");

            
            #line 18 "..\..\Views\Shared\Manage\Fields\FieldHeader.cshtml"
    }
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
