#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    #line 6 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
    using System.ComponentModel.DataAnnotations.Schema;
    
    #line default
    #line hidden
    using System.ComponentModel.Design;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Routing;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
    using LCore.Extensions;
    
    #line default
    #line hidden
    using LMVC;
    using LMVC.Account;
    using LMVC.Annotations;
    using LMVC.Context;
    using LMVC.Controllers;
    using LMVC.Extensions;
    using LMVC.Models;
    
    #line 3 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
    using LMVC.Routes;
    
    #line default
    #line hidden
    using Singularity;
    
    #line 5 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
    using Singularity.Extensions;
    
    #line default
    #line hidden
    using Singularity.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Manage/Fields/FieldView.cshtml")]
    public partial class _Views_Shared_Manage_Fields_FieldView_cshtml : System.Web.Mvc.WebViewPage<IViewField>
    {
        public _Views_Shared_Manage_Fields_FieldView_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 8 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
  
    bool ShowLabel = Model.ViewTypes.HasAny(ControllerHelper.ViewType.Create, ControllerHelper.ViewType.Edit, ControllerHelper.ViewType.Display);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n<div");

WriteAttribute("class", Tuple.Create(" class=\"", 397), Tuple.Create("\"", 552)
, Tuple.Create(Tuple.Create("", 405), Tuple.Create("field", 405), true)
            
            #line 15 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
, Tuple.Create(Tuple.Create(" ", 410), Tuple.Create<System.Object, System.Int32>(Model.ViewTypes.CollectStr((i,Type) => $"{Type.ToString().ToLower()}-field ")
            
            #line default
            #line hidden
, 411), false)
, Tuple.Create(Tuple.Create(" ", 489), Tuple.Create("field-", 490), true)
            
            #line 15 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                        , Tuple.Create(Tuple.Create("", 496), Tuple.Create<System.Object, System.Int32>(Model.ColumnClass
            
            #line default
            #line hidden
, 496), false)
            
            #line 15 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                          , Tuple.Create(Tuple.Create(" ", 514), Tuple.Create<System.Object, System.Int32>(Model.ModelFieldClasses.Combine(" ")
            
            #line default
            #line hidden
, 515), false)
);

WriteLiteral("\r\n     ");

            
            #line 16 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
Write(Html.Raw(Model.ModelFieldHtmlAttributes.Combine(" ")));

            
            #line default
            #line hidden
WriteLiteral("\r\n     data-object-type=\"");

            
            #line 17 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                  Write(Model.Meta.ModelType);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n     data-type-name=\"");

            
            #line 18 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                Write(Model.Meta.DataTypeName);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\r\n");

            
            #line 20 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
    
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
     if (Model.Meta.HasAttribute<ICustomPartial>() &&
                        Model.Meta.GetAttribute<ICustomPartial>().IsActive(Html, Model, Model.ViewTypes))
        {
        Model.Meta.GetAttribute<ICustomPartial>().RenderPartial(Html, Model, Model.ViewTypes);
        }
    else
        {
        if (Model.ViewTypes.Has(ControllerHelper.ViewType.TableCell) &&
            !Model.Meta.HasAttribute<NotMappedAttribute>(true) &&
            (Model.Meta.ModelType.PreferGeneric().HasInterface<IConvertible>() ||
            Model.Meta.ModelType.HasInterface<IModel>()))
            {
            string Data = (Model.PropertyData ?? "").ToString();

            if (Model.PropertyData is DateTime)
                {
                Data = ((DateTime)Model.PropertyData).ToShortDateString();
                }
            Data = Data.RemoveAll(" 12:00:00 AM");

            var Data1 = Model.PropertyData as IModel;
            if (Data1 != null)
                {
                Data = Data1.ToString();
                }

            if (!string.IsNullOrEmpty(Data))
                {

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteLiteral(" class=\"manage-view-show-similar\"");

WriteLiteral("\r\n                      data-field-name=\"");

            
            #line 49 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                  Write(Model.Meta.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                      data-field-value=\"");

            
            #line 50 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                   Write(Data);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("\r\n                      title=\"View Similar\"");

WriteLiteral(">\r\n                    <glyph>&#xe003;</glyph>\r\n                </span>\r\n");

            
            #line 54 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                }
            }

        if (ShowLabel)
            {
            string Label = Model.Meta.DisplayName ?? Model.Meta.PropertyName.Humanize();

            
            
            #line default
            #line hidden
            
            #line 61 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
       Write(Html.TextContent($"Manage_Edit_Field_Label_{Model.ModelData.GetFriendlyTypeName()}_{Label}",
                Html.Label(Model.Meta.PropertyName, Label)));

            
            #line default
            #line hidden
            
            #line 62 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                                           
            }

        if (Model.PropertyData == null)
            {
            
            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
       Write(Html.Partial(PartialViews.Manage.Fields.View.Empty, Model));

            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                                                       
            }
        else
            {
            if (Html.ViewExists(PartialViews.Manage.Fields.View.PropertyName(Model.PropertyName)))
                {
                // Override the Edit view for the property.

                
            
            #line default
            #line hidden
            
            #line 75 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
           Write(Html.Partial(PartialViews.Manage.Fields.View.PropertyName(Model.PropertyName)));

            
            #line default
            #line hidden
            
            #line 75 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                                                                               
                }
            else if (Model.Meta.AdditionalValues.ContainsKey(FieldStringFormatAttribute.Key) &&
                Model.PropertyData is IFormattable)
                {
                
            
            #line default
            #line hidden
            
            #line 80 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
           Write(Html.Partial(PartialViews.Manage.Fields.View.FormatString, Model));

            
            #line default
            #line hidden
            
            #line 80 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                                                                  
                }
            else if (Model.Meta.ModelType == typeof(bool) || Model.Meta.ModelType == typeof(bool?))
                {
                
            
            #line default
            #line hidden
            
            #line 84 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
           Write(Html.Partial(PartialViews.Manage.Fields.View.Boolean, Model));

            
            #line default
            #line hidden
            
            #line 84 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                                                             
                }
            else if (Model.Meta.DataTypeName == DataType.Currency.ToString())
                {
                
            
            #line default
            #line hidden
            
            #line 88 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
           Write(Html.Partial(PartialViews.Manage.Fields.View.Currency, Model));

            
            #line default
            #line hidden
            
            #line 88 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                                                              
                }
            else if (Model.Meta.ModelType == typeof(int) || Model.Meta.ModelType == typeof(int?))
                {
                
            
            #line default
            #line hidden
            
            #line 92 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
           Write(Html.Partial(PartialViews.Manage.Fields.View.Int, Model));

            
            #line default
            #line hidden
            
            #line 92 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                                                         
                }
            else if (Model.Meta.ModelType == typeof(DateTime) || Model.Meta.ModelType == typeof(DateTime?))
                {
                
            
            #line default
            #line hidden
            
            #line 96 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
           Write(Html.Partial(PartialViews.Manage.Fields.View.DateTime, Model));

            
            #line default
            #line hidden
            
            #line 96 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                                                              
                }
            else if (Model.ModelData.TrueModelType().HasAttribute<DisplayColumnAttribute>(true) &&
                Model.ModelData.TrueModelType().GetAttribute<DisplayColumnAttribute>(true).DisplayColumn == Model.Meta.PropertyName)
                {
                
            
            #line default
            #line hidden
            
            #line 101 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
           Write(Html.Partial(PartialViews.Manage.Fields.View.DisplayColumn, Model));

            
            #line default
            #line hidden
            
            #line 101 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                                                                   
                }
            else if (Model.Meta.ModelType.HasInterface<IModel>())
                {
                
            
            #line default
            #line hidden
            
            #line 105 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
           Write(Html.Partial(PartialViews.Manage.Fields.View.IModel, Model));

            
            #line default
            #line hidden
            
            #line 105 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                                                            
                }
            else if (Model.Meta.ModelType.HasInterface<IEnumerable>() &&
                Model.Meta.ModelType.IsGenericType &&
                Model.Meta.ModelType.GetGenericArguments()[0].HasInterface<IModel>())
                {
                
            
            #line default
            #line hidden
            
            #line 111 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
           Write(Html.Partial(PartialViews.Manage.Fields.View.IModelCollection, Model));

            
            #line default
            #line hidden
            
            #line 111 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                                                                      
                }
            else if (Model.Meta.ModelType.PreferGeneric().IsEnum)
                {
                
            
            #line default
            #line hidden
            
            #line 115 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
           Write(Html.Partial(PartialViews.Manage.Fields.View.Enum, Model));

            
            #line default
            #line hidden
            
            #line 115 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                                                          
                }
            else if (Html.ViewExists(PartialViews.Manage.Fields.View.PropertyType(Model.Meta.ModelType)))
                {
                
            
            #line default
            #line hidden
            
            #line 119 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
           Write(Html.Partial(PartialViews.Manage.Fields.View.PropertyType(Model.Meta.ModelType), Model));

            
            #line default
            #line hidden
            
            #line 119 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                                                                                        
                }
            else if (Html.ViewExists(PartialViews.Manage.Fields.View.DataTypeName(Model.Meta.DataTypeName)))
                {
                
            
            #line default
            #line hidden
            
            #line 123 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
           Write(Html.Partial(PartialViews.Manage.Fields.View.DataTypeName(Model.Meta.DataTypeName), Model));

            
            #line default
            #line hidden
            
            #line 123 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                                                                                           
                }
            else if (Model.Meta.ModelType == typeof(string))
                {
                
            
            #line default
            #line hidden
            
            #line 127 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
           Write(Html.Partial(PartialViews.Manage.Fields.View.String, Model));

            
            #line default
            #line hidden
            
            #line 127 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                                                            
                }
            else if (Model.Meta.ModelType == typeof(string[,]))
                {
                
            
            #line default
            #line hidden
            
            #line 131 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
           Write(Html.Partial(PartialViews.Manage.Fields.View.StringMatrix, Model));

            
            #line default
            #line hidden
            
            #line 131 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                                                                  
                }
            else if (Model.Meta.ModelType == typeof(string[][]))
                {
                
            
            #line default
            #line hidden
            
            #line 135 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
           Write(Html.Partial(PartialViews.Manage.Fields.View.StringMultiArray, Model));

            
            #line default
            #line hidden
            
            #line 135 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                                                                      
                }
            else
                {
                
            
            #line default
            #line hidden
            
            #line 139 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
           Write(Html.Partial(PartialViews.Manage.Fields.View.Unknown, Model));

            
            #line default
            #line hidden
            
            #line 139 "..\..\Views\Shared\Manage\Fields\FieldView.cshtml"
                                                                             
                }
            }
        }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

        }
    }
}
#pragma warning restore 1591
