#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.Design;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Routing;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LCore.Extensions;
    using Singularity;
    
    #line 3 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
    using Singularity.Annotations;
    
    #line default
    #line hidden
    using Singularity.Context;
    using Singularity.Controllers;
    
    #line 2 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
    using Singularity.Extensions;
    
    #line default
    #line hidden
    using Singularity.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Manage/Fields/Edit/Dropdown.cshtml")]
    public partial class _Views_Shared_Manage_Fields_Edit_Dropdown_cshtml : System.Web.Mvc.WebViewPage<IViewField>
    {
        public _Views_Shared_Manage_Fields_Edit_Dropdown_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
  
    var FieldAttr = Model.Meta.GetAttribute<FieldType_Dropdown>();

    bool Required = Model.Meta.IsRequired;

    string EmptyValue = FieldAttr.EmptyValue;
    string EmptyKey = FieldAttr.EmptyKey;

    List<SelectListItem> Items = FieldAttr.KeyValues(ViewContext).Select(keyValue => new SelectListItem
        {
        Text = keyValue.Key,
        Value = keyValue.Value,
        Selected = (Model.PropertyData ?? "").ToString() == keyValue.Value
        }).ToList();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 23 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
 if (FieldAttr.MultiSelect)
    {

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"option-checks\"");

WriteLiteral(">\r\n\r\n        <input");

WriteAttribute("name", Tuple.Create(" name=\"", 693), Tuple.Create("\"", 724)
            
            #line 27 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 700), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 700), false)
);

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" />\r\n\r\n");

            
            #line 29 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
        
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
         foreach (var Item in Items)
            {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"list-check\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"checkbox\"");

WriteAttribute("id", Tuple.Create("\r\n                       id=\"", 884), Tuple.Create("\"", 953)
            
            #line 33 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 913), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 913), false)
, Tuple.Create(Tuple.Create("", 939), Tuple.Create("_", 939), true)
            
            #line 33 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 940), Tuple.Create<System.Object, System.Int32>(Item.Value
            
            #line default
            #line hidden
, 940), false)
);

WriteAttribute("name", Tuple.Create("\r\n                       name=\"", 954), Tuple.Create("\"", 1009)
            
            #line 34 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 985), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 985), false)
);

WriteAttribute("value", Tuple.Create("\r\n                       value=\"", 1010), Tuple.Create("\"", 1053)
            
            #line 35 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 1042), Tuple.Create<System.Object, System.Int32>(Item.Value
            
            #line default
            #line hidden
, 1042), false)
);

WriteLiteral("\r\n                       ");

            
            #line 36 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
                   Write((Model.PropertyData ?? "").ToString().Contains(Item.Value) ? Html.Raw("checked=\"true\"") : Html.Raw(""));

            
            #line default
            #line hidden
WriteLiteral(">\r\n                <label");

WriteAttribute("for", Tuple.Create(" for=\"", 1211), Tuple.Create("\"", 1257)
            
            #line 37 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 1217), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 1217), false)
, Tuple.Create(Tuple.Create("", 1243), Tuple.Create("_", 1243), true)
            
            #line 37 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 1244), Tuple.Create<System.Object, System.Int32>(Item.Value
            
            #line default
            #line hidden
, 1244), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 38 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
               Write(Item.Text);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </label>\r\n            </div>\r\n");

            
            #line 41 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 43 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
    }
else
    {

            
            #line default
            #line hidden
WriteLiteral("    <select");

WriteAttribute("name", Tuple.Create(" name=\"", 1397), Tuple.Create("\"", 1428)
            
            #line 46 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 1404), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 1404), false)
);

WriteAttribute("id", Tuple.Create(" id=\"", 1429), Tuple.Create("\"", 1458)
            
            #line 46 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 1434), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 1434), false)
);

WriteLiteral(">\r\n");

            
            #line 47 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
        
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
         if (!Required)
            {

            
            #line default
            #line hidden
WriteLiteral("            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 1521), Tuple.Create("\"", 1540)
            
            #line 49 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 1529), Tuple.Create<System.Object, System.Int32>(EmptyValue
            
            #line default
            #line hidden
, 1529), false)
);

WriteLiteral(" ");

            
            #line 49 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
                                    Write((string)Model.PropertyData == EmptyValue ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 50 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
           Write(EmptyKey);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </option>\r\n");

            
            #line 52 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"

            }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 54 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
         foreach (var Item in Items)
            {

            
            #line default
            #line hidden
WriteLiteral("            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 1745), Tuple.Create("\"", 1764)
            
            #line 56 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
, Tuple.Create(Tuple.Create("", 1753), Tuple.Create<System.Object, System.Int32>(Item.Value
            
            #line default
            #line hidden
, 1753), false)
);

WriteLiteral(" ");

            
            #line 56 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
                                    Write(Item.Selected ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 57 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
           Write(Item.Text);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </option>\r\n");

            
            #line 59 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("    </select>\r\n");

            
            #line 61 "..\..\Views\Shared\Manage\Fields\Edit\Dropdown.cshtml"
    }
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
