#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.Design;
    using System.IO;
    
    #line 2 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Routing;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
    using LCore.Extensions;
    
    #line default
    #line hidden
    using Singularity;
    using Singularity.Context;
    using Singularity.Controllers;
    using Singularity.Extensions;
    using Singularity.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Manage/Fields/Edit/Enum.cshtml")]
    public partial class _Views_Shared_Manage_Fields_Edit_Enum_cshtml : System.Web.Mvc.WebViewPage<IViewField>
    {
        public _Views_Shared_Manage_Fields_Edit_Enum_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
  
    var EnumType = Model.Meta.ModelType.IsEnum ? Model.Meta.ModelType : Model.Meta.ModelType.GetGenericArguments()[0];

    var Values = Enum.GetValues(EnumType);

    IEnumerable<Enum> Enums = Values.Cast<Enum>();


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 16 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
 if (EnumType.HasAttribute<FlagsAttribute>(true))
    {

            
            #line default
            #line hidden
WriteLiteral("    <span");

WriteLiteral(" class=\"enum-checks\"");

WriteLiteral(">\r\n\r\n        <input");

WriteAttribute("name", Tuple.Create(" name=\"", 433), Tuple.Create("\"", 464)
            
            #line 20 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 440), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 440), false)
);

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" />\r\n\r\n");

            
            #line 22 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
        
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
         foreach (var e in Enums)
            {

            
            #line default
            #line hidden
WriteLiteral("            <span");

WriteLiteral(" class=\"enum-check\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"checkbox\"");

WriteAttribute("id", Tuple.Create("\r\n                       id=\"", 622), Tuple.Create("\"", 693)
            
            #line 26 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 651), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 651), false)
, Tuple.Create(Tuple.Create("", 677), Tuple.Create("_", 677), true)
            
            #line 26 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 678), Tuple.Create<System.Object, System.Int32>(e.ToString()
            
            #line default
            #line hidden
, 678), false)
);

WriteAttribute("name", Tuple.Create("\r\n                       name=\"", 694), Tuple.Create("\"", 749)
            
            #line 27 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 725), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 725), false)
);

WriteAttribute("value", Tuple.Create("\r\n                       value=\"", 750), Tuple.Create("\"", 795)
            
            #line 28 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 782), Tuple.Create<System.Object, System.Int32>(e.ToString()
            
            #line default
            #line hidden
, 782), false)
);

WriteLiteral("\r\n                       ");

            
            #line 29 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
                   Write((Model.PropertyData ?? "").ToString().Contains(e.ToString()) ? Html.Raw("checked=\"true\"") : Html.Raw(""));

            
            #line default
            #line hidden
WriteLiteral(">\r\n                <label");

WriteAttribute("for", Tuple.Create(" for=\"", 955), Tuple.Create("\"", 1003)
            
            #line 30 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 961), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 961), false)
, Tuple.Create(Tuple.Create("", 987), Tuple.Create("_", 987), true)
            
            #line 30 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 988), Tuple.Create<System.Object, System.Int32>(e.ToString()
            
            #line default
            #line hidden
, 988), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 31 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
               Write(e.GetFriendlyName());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </label>\r\n            </span>\r\n");

            
            #line 34 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("    </span>\r\n");

            
            #line 36 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
    }
else
    {
    List<SelectListItem> Items = Enums.Select(e => new SelectListItem
        {
        Text = e.GetFriendlyName(),
        Value = e.ToString(),
        Selected = (Model.PropertyData ?? "").ToString() == e.ToString()
        }).ToList();

    Items.Sort((Func<SelectListItem, IComparable>
        )(i => (IComparable)i.Text));


            
            #line default
            #line hidden
WriteLiteral("    <select");

WriteAttribute("name", Tuple.Create(" name=\"", 1495), Tuple.Create("\"", 1526)
            
            #line 49 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 1502), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 1502), false)
);

WriteAttribute("id", Tuple.Create(" id=\"", 1527), Tuple.Create("\"", 1556)
            
            #line 49 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 1532), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 1532), false)
);

WriteLiteral(">\r\n");

            
            #line 50 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
        
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
         foreach (var Item in Items)
            {

            
            #line default
            #line hidden
WriteLiteral("            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 1632), Tuple.Create("\"", 1651)
            
            #line 52 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 1640), Tuple.Create<System.Object, System.Int32>(Item.Value
            
            #line default
            #line hidden
, 1640), false)
);

WriteAttribute("selected", Tuple.Create(" selected=\"", 1652), Tuple.Create("\"", 1677)
            
            #line 52 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
, Tuple.Create(Tuple.Create("", 1663), Tuple.Create<System.Object, System.Int32>(Item.Selected
            
            #line default
            #line hidden
, 1663), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 53 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
           Write(Item.Text);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </option>\r\n");

            
            #line 55 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("    </select>\r\n");

            
            #line 57 "..\..\Views\Shared\Manage\Fields\Edit\Enum.cshtml"
    /*
                @Html.DropDownList(Model.Meta.PropertyName, Items, new { @class = "select-list" })
                */
    }

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
