#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.Design;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Routing;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LCore.Extensions;
    using Singularity;
    using Singularity.Context;
    using Singularity.Controllers;
    using Singularity.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Manage/Fields/Edit/Hidden.cshtml")]
    public partial class _Views_Shared_Manage_Fields_Edit_Hidden_cshtml : System.Web.Mvc.WebViewPage<IViewField>
    {
        public _Views_Shared_Manage_Fields_Edit_Hidden_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

            
            #line 3 "..\..\Views\Shared\Manage\Fields\Edit\Hidden.cshtml"
  

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("<input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("id", Tuple.Create("\r\n       id=\"", 78), Tuple.Create("\"", 115)
            
            #line 9 "..\..\Views\Shared\Manage\Fields\Edit\Hidden.cshtml"
, Tuple.Create(Tuple.Create("", 91), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 91), false)
);

WriteAttribute("name", Tuple.Create("\r\n       name=\"", 116), Tuple.Create("\"", 155)
            
            #line 10 "..\..\Views\Shared\Manage\Fields\Edit\Hidden.cshtml"
, Tuple.Create(Tuple.Create("", 131), Tuple.Create<System.Object, System.Int32>(Model.Meta.PropertyName
            
            #line default
            #line hidden
, 131), false)
);

WriteAttribute("value", Tuple.Create("\r\n       value=\"", 156), Tuple.Create("\"", 212)
            
            #line 11 "..\..\Views\Shared\Manage\Fields\Edit\Hidden.cshtml"
, Tuple.Create(Tuple.Create("", 172), Tuple.Create<System.Object, System.Int32>((Model.PropertyData ?? "").ToString()
            
            #line default
            #line hidden
, 172), false)
);

WriteLiteral(" />");

        }
    }
}
#pragma warning restore 1591
