#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.Design;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Routing;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\Manage\Fields\View\DateTime.cshtml"
    using LCore.Extensions;
    
    #line default
    #line hidden
    using Singularity;
    using Singularity.Context;
    using Singularity.Controllers;
    using Singularity.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Manage/Fields/View/DateTime.cshtml")]
    public partial class _Views_Shared_Manage_Fields_View_DateTime_cshtml : System.Web.Mvc.WebViewPage<IViewField>
    {
        public _Views_Shared_Manage_Fields_View_DateTime_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Shared\Manage\Fields\View\DateTime.cshtml"
  
    var CurrentValue = (DateTime?)Model.ModelData.GetProperty(Model.Meta.PropertyName);


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n");

            
            #line 12 "..\..\Views\Shared\Manage\Fields\View\DateTime.cshtml"
 if (CurrentValue == null || (DateTime)CurrentValue == DateTime.MinValue)
    {

    }
else if (Model.Meta.DataTypeName == DataType.Date.ToString())
    {

            
            #line default
            #line hidden
WriteLiteral("    <span>\r\n");

WriteLiteral("        ");

            
            #line 19 "..\..\Views\Shared\Manage\Fields\View\DateTime.cshtml"
    Write(((DateTime)CurrentValue).ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </span>\r\n");

            
            #line 21 "..\..\Views\Shared\Manage\Fields\View\DateTime.cshtml"
    }
else if (Model.Meta.DataTypeName == DataType.Time.ToString())
    {

            
            #line default
            #line hidden
WriteLiteral("    <span>\r\n");

WriteLiteral("        ");

            
            #line 25 "..\..\Views\Shared\Manage\Fields\View\DateTime.cshtml"
    Write(((DateTime)CurrentValue).ToShortTimeString());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </span>\r\n");

            
            #line 27 "..\..\Views\Shared\Manage\Fields\View\DateTime.cshtml"
    }
else if (Model.Meta.DataTypeName == DataType.DateTime.ToString())
    {

            
            #line default
            #line hidden
WriteLiteral("    <span>\r\n");

WriteLiteral("        ");

            
            #line 31 "..\..\Views\Shared\Manage\Fields\View\DateTime.cshtml"
    Write(((DateTime)CurrentValue).ToString());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </span>\r\n");

            
            #line 33 "..\..\Views\Shared\Manage\Fields\View\DateTime.cshtml"
    }
else
    {

            
            #line default
            #line hidden
WriteLiteral("    <span>\r\n");

WriteLiteral("        ");

            
            #line 37 "..\..\Views\Shared\Manage\Fields\View\DateTime.cshtml"
    Write(((DateTime)CurrentValue).ToString());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </span>\r\n");

            
            #line 39 "..\..\Views\Shared\Manage\Fields\View\DateTime.cshtml"
    }

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
