#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.Design;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Routing;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\Manage\Fields\View\IModel.cshtml"
    using LCore.Extensions;
    
    #line default
    #line hidden
    using Singularity;
    using Singularity.Context;
    using Singularity.Controllers;
    
    #line 2 "..\..\Views\Shared\Manage\Fields\View\IModel.cshtml"
    using Singularity.Extensions;
    
    #line default
    #line hidden
    using Singularity.Models;
    
    #line 5 "..\..\Views\Shared\Manage\Fields\View\IModel.cshtml"
    using Singularity.Routes;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Manage/Fields/View/IModel.cshtml")]
    public partial class _Views_Shared_Manage_Fields_View_IModel_cshtml : System.Web.Mvc.WebViewPage<IViewField>
    {
        public _Views_Shared_Manage_Fields_View_IModel_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\Shared\Manage\Fields\View\IModel.cshtml"
  

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 12 "..\..\Views\Shared\Manage\Fields\View\IModel.cshtml"
 if (Model.PropertyData != null && 
    Model.PropertyData.ToString().Length > ControllerHelper.DefaultTableTextLength)
    {

            
            #line default
            #line hidden
WriteLiteral("    <a");

WriteLiteral(" class=\"btn btn-default\"");

WriteAttribute("title", Tuple.Create("\r\n       title=\"", 356), Tuple.Create("\"", 402)
            
            #line 16 "..\..\Views\Shared\Manage\Fields\View\IModel.cshtml"
, Tuple.Create(Tuple.Create("", 372), Tuple.Create<System.Object, System.Int32>(Model.PropertyData.ToString()
            
            #line default
            #line hidden
, 372), false)
);

WriteAttribute("href", Tuple.Create("\r\n       href=\"", 403), Tuple.Create("\"", 468)
            
            #line 17 "..\..\Views\Shared\Manage\Fields\View\IModel.cshtml"
, Tuple.Create(Tuple.Create("", 418), Tuple.Create<System.Object, System.Int32>(Model.Route_FieldRelation(ViewBag.ControllerName)
            
            #line default
            #line hidden
, 418), false)
);

WriteLiteral(">\r\n        <span>\r\n");

WriteLiteral("            ");

            
            #line 19 "..\..\Views\Shared\Manage\Fields\View\IModel.cshtml"
       Write(Model.PropertyData.ToString().Substring(0, ControllerHelper.DefaultTableTextLength));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n    </a>\r\n");

            
            #line 22 "..\..\Views\Shared\Manage\Fields\View\IModel.cshtml"
    }
else
    {

            
            #line default
            #line hidden
WriteLiteral("    <a");

WriteLiteral(" class=\"btn btn-default\"");

WriteAttribute("href", Tuple.Create("\r\n       href=\"", 663), Tuple.Create("\"", 728)
            
            #line 26 "..\..\Views\Shared\Manage\Fields\View\IModel.cshtml"
, Tuple.Create(Tuple.Create("", 678), Tuple.Create<System.Object, System.Int32>(Model.Route_FieldRelation(ViewBag.ControllerName)
            
            #line default
            #line hidden
, 678), false)
);

WriteLiteral(">\r\n        <span>\r\n");

WriteLiteral("            ");

            
            #line 28 "..\..\Views\Shared\Manage\Fields\View\IModel.cshtml"
       Write(Model.PropertyData.ToString());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n    </a>\r\n");

            
            #line 31 "..\..\Views\Shared\Manage\Fields\View\IModel.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 33 "..\..\Views\Shared\Manage\Fields\View\IModel.cshtml"
 if (Model.PropertyData != null && 
    ViewContext.AllowEdit(Model.FieldType) &&
    !Model.ViewTypes.Has(ControllerHelper.ViewType.TableCell))
    {

            
            #line default
            #line hidden
WriteLiteral("    <a");

WriteLiteral(" class=\"btn btn-default\"");

WriteAttribute("href", Tuple.Create("\r\n       href=\"", 1013), Tuple.Create("\"", 1269)
            
            #line 38 "..\..\Views\Shared\Manage\Fields\View\IModel.cshtml"
, Tuple.Create(Tuple.Create("", 1028), Tuple.Create<System.Object, System.Int32>(Url.Action(nameof(ManageController.Edit),
        ContextProviderFactory.GetCurrent().GetManageController(Session, Model.FieldType).Name,
        Controllers.Manage.Actions.Route_Edit((IModel)Model.PropertyData, Request.Url?.AbsoluteUri))
            
            #line default
            #line hidden
, 1028), false)
);

WriteLiteral(">\r\n        <span>\r\n            <glyph>&#xe065;</glyph>\r\n            Edit\r\n       " +
" </span>\r\n    </a>\r\n");

            
            #line 46 "..\..\Views\Shared\Manage\Fields\View\IModel.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 48 "..\..\Views\Shared\Manage\Fields\View\IModel.cshtml"
 if (Model.PropertyData == null && 
    ViewContext.AllowCreate(Model.FieldType) &&
    !Model.ViewTypes.Has(ControllerHelper.ViewType.TableCell))
    {

            
            #line default
            #line hidden
WriteLiteral("    <a");

WriteLiteral(" class=\"btn btn-default\"");

WriteAttribute("href", Tuple.Create("\r\n       href=\"", 1567), Tuple.Create("\"", 1799)
            
            #line 53 "..\..\Views\Shared\Manage\Fields\View\IModel.cshtml"
, Tuple.Create(Tuple.Create("", 1582), Tuple.Create<System.Object, System.Int32>(Url.Action(nameof(ManageController.Create),
        ContextProviderFactory.GetCurrent().GetManageController(Session, Model.FieldType).Name,
        Controllers.Manage.Actions.Route_Create(Request.Url?.AbsoluteUri))
            
            #line default
            #line hidden
, 1582), false)
);

WriteLiteral(">\r\n        <span>\r\n            <glyph>&#x2a;</glyph>\r\n            Create\r\n       " +
" </span>\r\n    </a>\r\n");

            
            #line 61 "..\..\Views\Shared\Manage\Fields\View\IModel.cshtml"
    }
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
