#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    
    #line 8 "..\..\Views\Shared\Fields\Information.cshtml"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Views\Shared\Fields\Information.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 10 "..\..\Views\Shared\Fields\Information.cshtml"
    using System.ComponentModel;
    
    #line default
    #line hidden
    
    #line 16 "..\..\Views\Shared\Fields\Information.cshtml"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 17 "..\..\Views\Shared\Fields\Information.cshtml"
    using System.ComponentModel.DataAnnotations.Schema;
    
    #line default
    #line hidden
    
    #line 11 "..\..\Views\Shared\Fields\Information.cshtml"
    using System.ComponentModel.Design;
    
    #line default
    #line hidden
    using System.IO;
    
    #line 14 "..\..\Views\Shared\Fields\Information.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 15 "..\..\Views\Shared\Fields\Information.cshtml"
    using System.Linq.Expressions;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    
    #line 12 "..\..\Views\Shared\Fields\Information.cshtml"
    using System.Web;
    
    #line default
    #line hidden
    using System.Web.Helpers;
    
    #line 13 "..\..\Views\Shared\Fields\Information.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\Fields\Information.cshtml"
    using LCore;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\Fields\Information.cshtml"
    using MVCL;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Shared\Fields\Information.cshtml"
    using MVCL.Context;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\Shared\Fields\Information.cshtml"
    using MVCL.Controllers;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Shared\Fields\Information.cshtml"
    using MVCL.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Fields/Information.cshtml")]
    public partial class _Views_Shared_Fields_Information_cshtml : System.Web.Mvc.WebViewPage<IViewField>
    {
        public _Views_Shared_Fields_Information_cshtml()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n\r\n");
















WriteLiteral("\r\n");


            
            #line 19 "..\..\Views\Shared\Fields\Information.cshtml"
  



            
            #line default
            #line hidden
WriteLiteral("\r\n");


WriteLiteral("\r\n");


            
            #line 25 "..\..\Views\Shared\Fields\Information.cshtml"
 if (Model.Meta.AdditionalValues.ContainsKey(InformationAttribute.Key))
{

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"field-information\">\r\n        <p>\r\n            <glyph>&#xE086;</gl" +
"yph>\r\n            ");


            
            #line 30 "..\..\Views\Shared\Fields\Information.cshtml"
       Write(Model.Meta.AdditionalValues[InformationAttribute.Key]);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n    </div>\r\n");


            
            #line 33 "..\..\Views\Shared\Fields\Information.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
