#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    
    #line 8 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 10 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
    using System.ComponentModel;
    
    #line default
    #line hidden
    
    #line 16 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 17 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
    using System.ComponentModel.DataAnnotations.Schema;
    
    #line default
    #line hidden
    
    #line 11 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
    using System.ComponentModel.Design;
    
    #line default
    #line hidden
    using System.IO;
    
    #line 14 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 15 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
    using System.Linq.Expressions;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    
    #line 12 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
    using System.Web;
    
    #line default
    #line hidden
    using System.Web.Helpers;
    
    #line 13 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
    using LCore;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
    using MVCL;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
    using MVCL.Context;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
    using MVCL.Controllers;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
    using MVCL.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Fields/View/StringMultiArray.cshtml")]
    public partial class _Views_Shared_Fields_View_StringMultiArray_cshtml : System.Web.Mvc.WebViewPage<IViewField>
    {
        public _Views_Shared_Fields_View_StringMultiArray_cshtml()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n\r\n");
















WriteLiteral("\r\n");


            
            #line 19 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
  
    String[][] TableData = (String[][])Model.PropertyData;


            
            #line default
            #line hidden
WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n<table class=\"string-multiarray\">\r\n");


            
            #line 27 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
     for (int i = 0; i < TableData.Length; i++)
        {
        if (i == 0)
            {
            
            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
       Write(Html.Raw("<thead>"));

            
            #line default
            #line hidden
            
            #line 31 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
                                ;
            }


            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n");


            
            #line 35 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
                 for (int j = 0; j < TableData[i].Length; j++)
                    {

            
            #line default
            #line hidden
WriteLiteral("                    <td>\r\n");


            
            #line 38 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
                         if (TableData[i][j].ToString().Length > ManageController.DefaultTableTextLength)
                            {

            
            #line default
            #line hidden
WriteLiteral("                            <span class=\"abbreviated\" title=\"");


            
            #line 40 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
                                                        Write(Model.PropertyData);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                ");


            
            #line 41 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
                           Write(TableData[i][j].Substring(0, ManageController.DefaultTableTextLength));

            
            #line default
            #line hidden
WriteLiteral(" ...\r\n                            </span>\r\n");


            
            #line 43 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
                            }
                        else
                            {

            
            #line default
            #line hidden
WriteLiteral("                            <span>\r\n                                ");


            
            #line 47 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
                           Write(TableData[i][j]);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </span>\r\n");


            
            #line 49 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n");


            
            #line 51 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n            </tr>\r\n");


            
            #line 54 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"

        if (i == 0)
            {
            
            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
       Write(Html.Raw("</thead>"));

            
            #line default
            #line hidden
            
            #line 57 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
                                 ;
            }

        if (TableData.Length == 1)
            {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td colspan=\"");


            
            #line 63 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
                        Write(TableData[i].Length);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                    &nbsp;\r\n                </td>\r\n            </tr>\r\n");


            
            #line 67 "..\..\Views\Shared\Fields\View\StringMultiArray.cshtml"
            }

        }

            
            #line default
            #line hidden
WriteLiteral("</table>");


        }
    }
}
#pragma warning restore 1591
