#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.Design;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Routing;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Shared\TextContent.cshtml"
    using LCore.Extensions;
    
    #line default
    #line hidden
    using Singularity;
    using Singularity.Context;
    using Singularity.Controllers;
    
    #line 5 "..\..\Views\Shared\TextContent.cshtml"
    using Singularity.Extensions;
    
    #line default
    #line hidden
    using Singularity.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/TextContent.cshtml")]
    public partial class _Views_Shared_TextContent_cshtml : System.Web.Mvc.WebViewPage<TextContentViewModel>
    {
        public _Views_Shared_TextContent_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n\r\n");

WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\Shared\TextContent.cshtml"
  
    TextContent Content = null;
    ModelPermissions Permissions = null;
    string Display = null;
    string Token = null;

    try
        {

        Token = Model.Token ?? "";

        Token = Token.ReplaceAll(" ", "");

        ContextProvider ContextProvider = ContextProviderFactory.GetCurrent();
        ModelContext Context = ContextProvider.GetContext(Session);

        Content = TextContent.FindByToken(Context, Token);

        // Auto-create TextContent models so they exist before being filled in
        if (Content == null && Model.AutoCreate)
            {
            Content = new TextContent
                {
                Active = true,
                Token = Model.Token,
                Text = Model.DefaultText
                };

            Context.GetDBSet<TextContent>().Add(Content);

            Context.SaveChanges();
            }

        Permissions = ContextProvider.GetModelPermissions(Session, typeof(TextContent));

        Display = Content != null ? Content.Text : Model.DefaultText;
        Display = Display ?? "";

        for (int i = 0; i < Model.ContextData.Length; i++)
            {
            Display = Display.ReplaceAll($"[{i}]", (Model.ContextData[i] ?? "").ToString());
            }

        Display = Display.ReplaceAll("\r\n", "<br>");
        }
    catch
        {

        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 59 "..\..\Views\Shared\TextContent.cshtml"
 try
    {

    if (Content != null)
        {

            
            #line default
            #line hidden
WriteLiteral("        <span");

WriteLiteral(" class=\"text-content-custom\"");

WriteLiteral(">\r\n");

            
            #line 65 "..\..\Views\Shared\TextContent.cshtml"
            
            
            #line default
            #line hidden
            
            #line 65 "..\..\Views\Shared\TextContent.cshtml"
             if (Model.ShowText)
                {
                
            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\Shared\TextContent.cshtml"
           Write(Html.Raw(Display));

            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\Shared\TextContent.cshtml"
                                  
                }
            else
                {

            
            #line default
            #line hidden
WriteLiteral("                <span>...</span>\r\n");

            
            #line 72 "..\..\Views\Shared\TextContent.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 73 "..\..\Views\Shared\TextContent.cshtml"
             if (Permissions != null && Permissions.Edit == true)
                {

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteAttribute("class", Tuple.Create(" class=\"", 1916), Tuple.Create("\"", 1977)
, Tuple.Create(Tuple.Create("", 1924), Tuple.Create("text-content-edit", 1924), true)
            
            #line 75 "..\..\Views\Shared\TextContent.cshtml"
, Tuple.Create(Tuple.Create(" ", 1941), Tuple.Create<System.Object, System.Int32>(Model.ShowText ? "" : "no-text" 
            
            #line default
            #line hidden
, 1942), false)
);

WriteLiteral(">\r\n\r\n                    <span");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 2008), Tuple.Create("\"", 2334)
, Tuple.Create(Tuple.Create("", 2018), Tuple.Create("window.location", 2018), true)
, Tuple.Create(Tuple.Create(" ", 2033), Tuple.Create("=", 2034), true)
, Tuple.Create(Tuple.Create(" ", 2035), Tuple.Create("\'", 2036), true)
            
            #line 77 "..\..\Views\Shared\TextContent.cshtml"
, Tuple.Create(Tuple.Create("", 2037), Tuple.Create<System.Object, System.Int32>(Url.Controller<TextContentController>()
                    .QS(new Dictionary<string, object> { { "Token", Token }, { "DefaultText", HttpUtility.HtmlEncode(Model.DefaultText) } })
                    .Action(c => c.Edit, Content.GetID<int>(), Request.Url?.AbsoluteUri, false)
            
            #line default
            #line hidden
, 2037), false)
, Tuple.Create(Tuple.Create("", 2318), Tuple.Create("\';", 2318), true)
, Tuple.Create(Tuple.Create(" ", 2320), Tuple.Create("return", 2321), true)
, Tuple.Create(Tuple.Create(" ", 2327), Tuple.Create("false;", 2328), true)
);

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(">\r\n                        <glyph>&#xe065;</glyph>\r\n                    </span>\r\n" +
"                </span>\r\n");

            
            #line 83 "..\..\Views\Shared\TextContent.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("        </span>\r\n");

            
            #line 85 "..\..\Views\Shared\TextContent.cshtml"
        }
    else
        {

            
            #line default
            #line hidden
WriteLiteral("        <span");

WriteLiteral(" class=\"text-content-default\"");

WriteLiteral(">\r\n");

            
            #line 89 "..\..\Views\Shared\TextContent.cshtml"
            
            
            #line default
            #line hidden
            
            #line 89 "..\..\Views\Shared\TextContent.cshtml"
             if (Model.ShowText)
                {
                
            
            #line default
            #line hidden
            
            #line 91 "..\..\Views\Shared\TextContent.cshtml"
           Write(Html.Raw(Display));

            
            #line default
            #line hidden
            
            #line 91 "..\..\Views\Shared\TextContent.cshtml"
                                  
                }
            else
                {

            
            #line default
            #line hidden
WriteLiteral("                <span>...</span>\r\n");

            
            #line 96 "..\..\Views\Shared\TextContent.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            ");

            
            #line 97 "..\..\Views\Shared\TextContent.cshtml"
             if (Permissions != null && Permissions.Create == true)
                {

            
            #line default
            #line hidden
WriteLiteral("                <span");

WriteAttribute("class", Tuple.Create(" class=\"", 2885), Tuple.Create("\"", 2947)
, Tuple.Create(Tuple.Create("", 2893), Tuple.Create("text-content-create", 2893), true)
            
            #line 99 "..\..\Views\Shared\TextContent.cshtml"
, Tuple.Create(Tuple.Create(" ", 2912), Tuple.Create<System.Object, System.Int32>(Model.ShowText ? "" : "no-text"
            
            #line default
            #line hidden
, 2913), false)
);

WriteLiteral(">\r\n\r\n\r\n                    <span");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 2980), Tuple.Create("\"", 3279)
, Tuple.Create(Tuple.Create("", 2990), Tuple.Create("window.location", 2990), true)
, Tuple.Create(Tuple.Create(" ", 3005), Tuple.Create("=", 3006), true)
, Tuple.Create(Tuple.Create(" ", 3007), Tuple.Create("\'", 3008), true)
            
            #line 102 "..\..\Views\Shared\TextContent.cshtml"
, Tuple.Create(Tuple.Create("", 3009), Tuple.Create<System.Object, System.Int32>(Url.Controller<TextContentController>()
                    .QS(new Dictionary<string, object> { { "Token", Token }, { "DefaultText", HttpUtility.HtmlEncode(Model.DefaultText) } })
                    .Action(c => c.Create, Request.Url?.AbsoluteUri)
            
            #line default
            #line hidden
, 3009), false)
, Tuple.Create(Tuple.Create("", 3263), Tuple.Create("\';", 3263), true)
, Tuple.Create(Tuple.Create(" ", 3265), Tuple.Create("return", 3266), true)
, Tuple.Create(Tuple.Create(" ", 3272), Tuple.Create("false;", 3273), true)
);

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(">\r\n                        <glyph>&#xe065;</glyph>\r\n                    </span>\r\n" +
"                </span>\r\n");

            
            #line 108 "..\..\Views\Shared\TextContent.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("        </span>\r\n");

            
            #line 110 "..\..\Views\Shared\TextContent.cshtml"
        }
    }
catch
    {
    }
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
