#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    
    #line 8 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 10 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
    using System.ComponentModel;
    
    #line default
    #line hidden
    
    #line 16 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 17 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
    using System.ComponentModel.DataAnnotations.Schema;
    
    #line default
    #line hidden
    
    #line 11 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
    using System.ComponentModel.Design;
    
    #line default
    #line hidden
    using System.IO;
    
    #line 14 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 15 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
    using System.Linq.Expressions;
    
    #line default
    #line hidden
    using System.Net;
    using System.Text;
    
    #line 12 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
    using System.Web;
    
    #line default
    #line hidden
    using System.Web.Helpers;
    
    #line 13 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
    using System.Web.Mvc;
    
    #line default
    #line hidden
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
    using LCore;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
    using MVCL;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
    using MVCL.Context;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
    using MVCL.Controllers;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
    using MVCL.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Fields/Edit/IntRange.cshtml")]
    public partial class _Views_Shared_Fields_Edit_IntRange_cshtml : System.Web.Mvc.WebViewPage<IViewField>
    {
        public _Views_Shared_Fields_Edit_IntRange_cshtml()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n\r\n");
















WriteLiteral("\r\n");


            
            #line 19 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
  
    RangeAttribute Attr = Model.Meta.GetAttribute<RangeAttribute>();


            
            #line default
            #line hidden
WriteLiteral("\r\n");


WriteLiteral("\r\n<div class=\"int-range\"\r\n     target=\"");


            
            #line 26 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
        Write(Model.Meta.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n     text-target=\"");


            
            #line 27 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
              Write(Model.Meta.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("_Text\"\r\n     value=\"");


            
            #line 28 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
       Write(Model.ModelData.GetProperty(Model.Meta.PropertyName));

            
            #line default
            #line hidden
WriteLiteral("\"\r\n     maximum=\"");


            
            #line 29 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
         Write(Attr.Maximum);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n     minimum=\"");


            
            #line 30 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
         Write(Attr.Minimum);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n</div>\r\n\r\n<div id=\"");


            
            #line 33 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
     Write(Model.Meta.PropertyName);

            
            #line default
            #line hidden
WriteLiteral("_Text\" class=\"int-range-display\">\r\n    ");


            
            #line 34 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
Write(Model.ModelData.GetProperty(Model.Meta.PropertyName));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n");


            
            #line 37 "..\..\Views\Shared\Fields\Edit\IntRange.cshtml"
Write(Html.Hidden(Model.Meta.PropertyName));

            
            #line default
            #line hidden
WriteLiteral(";");


        }
    }
}
#pragma warning restore 1591
