#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.Design;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Routing;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Shared\Details.cshtml"
    using LCore.Extensions;
    
    #line default
    #line hidden
    using Singularity;
    
    #line 7 "..\..\Views\Shared\Details.cshtml"
    using Singularity.Annotations;
    
    #line default
    #line hidden
    using Singularity.Context;
    using Singularity.Controllers;
    
    #line 6 "..\..\Views\Shared\Details.cshtml"
    using Singularity.Extensions;
    
    #line default
    #line hidden
    using Singularity.Models;
    
    #line 5 "..\..\Views\Shared\Details.cshtml"
    using Singularity.Routes;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Details.cshtml")]
    public partial class _Views_Shared_Details_cshtml : System.Web.Mvc.WebViewPage<IModel>
    {
        public _Views_Shared_Details_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n\r\n");

WriteLiteral("\r\n");

            
            #line 9 "..\..\Views\Shared\Details.cshtml"
  
    ViewBag.Title = "Details";
    Layout = Layouts.MainLayout;

    const ControllerHelper.ViewType ViewType = ControllerHelper.ViewType.Display;

    IFieldGroups model = Model as IFieldGroups;

    IEnumerable<ModelMetadata> Fields = model != null ? model.GetFieldGroup(Context, ViewType) : FieldGroups.GetFieldGroup(Context, Model.TrueModelType(), ViewType);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"details wide-form\"");

WriteLiteral(">\r\n\r\n");

            
            #line 24 "..\..\Views\Shared\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Shared\Details.cshtml"
     if (!string.IsNullOrEmpty(ViewBag.ReturnURL))
        {
        if (ViewContext.AllowEdit(Model.TrueModelType()))
            {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteLiteral(" class=\"btn-default right\"");

WriteAttribute("href", Tuple.Create("\r\n               href=\"", 760), Tuple.Create("\"", 893)
            
            #line 29 "..\..\Views\Shared\Details.cshtml"
, Tuple.Create(Tuple.Create("", 783), Tuple.Create<System.Object, System.Int32>(Url.Controller<ManageController>().Action(c => c.Edit, Model.GetID<int>(), Request.Url?.AbsoluteUri, false)
            
            #line default
            #line hidden
, 783), false)
);

WriteLiteral(">\r\n                <glyph>&#xe065;</glyph>\r\n                Edit\r\n            </a" +
">\r\n");

            
            #line 33 "..\..\Views\Shared\Details.cshtml"
            }


            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteLiteral(" class=\"btn-default right\"");

WriteAttribute("href", Tuple.Create(" href=\"", 1035), Tuple.Create("\"", 1060)
            
            #line 35 "..\..\Views\Shared\Details.cshtml"
, Tuple.Create(Tuple.Create("", 1042), Tuple.Create<System.Object, System.Int32>(ViewBag.ReturnURL
            
            #line default
            #line hidden
, 1042), false)
);

WriteLiteral(">\r\n                <glyph>&#xe091;</glyph>\r\n                Back\r\n            </a" +
">\r\n");

            
            #line 39 "..\..\Views\Shared\Details.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <h1>\r\n");

WriteLiteral("        ");

            
            #line 42 "..\..\Views\Shared\Details.cshtml"
   Write(Model.GetFriendlyTypeName());

            
            #line default
            #line hidden
WriteLiteral(" Details\r\n    </h1>\r\n\r\n    <h2>\r\n");

WriteLiteral("        ");

            
            #line 46 "..\..\Views\Shared\Details.cshtml"
   Write(Model.ToString());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </h2>\r\n\r\n");

            
            #line 49 "..\..\Views\Shared\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Shared\Details.cshtml"
     foreach (ModelMetadata Meta in Fields)
        {
        Meta.PropertyName.ToUrlSlug();

        ViewField Field = new ViewField(ViewContext, Model.TrueModelType(), Meta.PropertyName, Model, ViewType);

        
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\Shared\Details.cshtml"
   Write(Html.ViewField(Field));

            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\Shared\Details.cshtml"
                              
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 58 "..\..\Views\Shared\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 58 "..\..\Views\Shared\Details.cshtml"
     if (!string.IsNullOrEmpty(ViewBag.ReturnURL))
        {
        if (ViewContext.AllowEdit(Model.TrueModelType()))
            {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteLiteral(" class=\"btn-default right\"");

WriteAttribute("href", Tuple.Create(" \r\n               href=\"", 1713), Tuple.Create("\"", 1847)
            
            #line 63 "..\..\Views\Shared\Details.cshtml"
, Tuple.Create(Tuple.Create("", 1737), Tuple.Create<System.Object, System.Int32>(Url.Controller<ManageController>().Action(c => c.Edit, Model.GetID<int>(), Request.Url?.AbsoluteUri, false)
            
            #line default
            #line hidden
, 1737), false)
);

WriteLiteral("\r\n               key-bind-click=\"Ctrl+E\"");

WriteLiteral("\r\n               key-bind-click-name=\"Edit\"");

WriteLiteral(">\r\n                <glyph>&#xe065;</glyph>\r\n                Edit\r\n            </a" +
">\r\n");

            
            #line 69 "..\..\Views\Shared\Details.cshtml"
            }


            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteLiteral(" class=\"btn-default right\"");

WriteAttribute("href", Tuple.Create("\r\n               href=\"", 2072), Tuple.Create("\"", 2113)
            
            #line 72 "..\..\Views\Shared\Details.cshtml"
, Tuple.Create(Tuple.Create("", 2095), Tuple.Create<System.Object, System.Int32>(ViewBag.ReturnURL
            
            #line default
            #line hidden
, 2095), false)
);

WriteLiteral("\r\n               key-bind-click=\"Esc\"");

WriteLiteral("\r\n               key-bind-click-name=\"Back\"");

WriteLiteral(">\r\n                <glyph>&#xe091;</glyph>\r\n                Back\r\n            </a" +
">\r\n");

            
            #line 78 "..\..\Views\Shared\Details.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
