#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.Design;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Routing;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LCore.Extensions;
    using LMVC;
    using LMVC.Account;
    using LMVC.Annotations;
    using LMVC.Context;
    using LMVC.Controllers;
    using LMVC.Extensions;
    using LMVC.Models;
    
    #line 3 "..\..\Views\Shared\Nav.cshtml"
    using LMVC.Routes;
    
    #line default
    #line hidden
    using Singularity;
    using Singularity.Extensions;
    using Singularity.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Nav.cshtml")]
    public partial class _Views_Shared_Nav_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_Nav_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 5 "..\..\Views\Shared\Nav.cshtml"
  
    var Context = ContextProviderFactory.GetCurrent();



            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<nav");

WriteLiteral(" class=\"navbar navbar-inverse navbar-fixed-top\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Views\Shared\Nav.cshtml"
   Write(Html.Partial(PartialViews.LoginPartial));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\"#bs-example-navbar-collapse-1\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle navigation</span>\r\n                <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n            </button>\r\n            <a");

WriteLiteral(" class=\"navbar-brand\"");

WriteLiteral(" href=\"/\"");

WriteLiteral(">");

            
            #line 23 "..\..\Views\Shared\Nav.cshtml"
                                        Write(Context.SiteTitle);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"collapse navbar-collapse\"");

WriteLiteral(" id=\"bs-example-navbar-collapse-1\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\r\n                <li>\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">About</a>\r\n                </li>\r\n                <li>\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Services</a>\r\n                </li>\r\n                <li>\r\n                    <" +
"a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Contact</a>\r\n                </li>\r\n            </ul>\r\n        </div>\r\n\r\n\r\n     " +
"   <div");

WriteLiteral(" class=\"key-bind-tip\"");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"border-bottom\"");

WriteLiteral(">\r\n                <glyph>&#xe047;</glyph>\r\n                Key Shortcuts\r\n      " +
"      </div>\r\n            <span");

WriteLiteral(" id=\"key-bind-page-tip\"");

WriteLiteral(">\r\n            </span>\r\n        </div>\r\n\r\n    </div>\r\n\r\n</nav>\r\n\r\n<div");

WriteLiteral(" class=\"nav-spacer\"");

WriteLiteral(">&nbsp;</div>");

        }
    }
}
#pragma warning restore 1591
