#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.Design;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Routing;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Shared\Manage\Details.cshtml"
    using LCore.Extensions;
    
    #line default
    #line hidden
    using Singularity;
    
    #line 6 "..\..\Views\Shared\Manage\Details.cshtml"
    using Singularity.Annotations;
    
    #line default
    #line hidden
    using Singularity.Context;
    using Singularity.Controllers;
    
    #line 5 "..\..\Views\Shared\Manage\Details.cshtml"
    using Singularity.Extensions;
    
    #line default
    #line hidden
    using Singularity.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Manage/Details.cshtml")]
    public partial class _Views_Shared_Manage_Details_cshtml : System.Web.Mvc.WebViewPage<IModel>
    {
        public _Views_Shared_Manage_Details_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n\r\n");

WriteLiteral("\r\n");

            
            #line 8 "..\..\Views\Shared\Manage\Details.cshtml"
  
    ViewBag.Title = "Details";

    const ControllerHelper.ViewType ViewType = ControllerHelper.ViewType.Display;

    var model = Model as IFieldGroups;

    IEnumerable<ModelMetadata> Fields = model != null ? model.GetFieldGroup(Context, ViewType) : FieldGroups.GetFieldGroup(Context, Model.TrueModelType(), ViewType);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"details wide-form\"");

WriteLiteral(">\r\n\r\n");

            
            #line 22 "..\..\Views\Shared\Manage\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Shared\Manage\Details.cshtml"
     if (!string.IsNullOrEmpty(ViewBag.ReturnURL))
        {
        if (ViewContext.AllowEdit(Model.TrueModelType()))
            {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteLiteral(" class=\"btn-default right\"");

WriteAttribute("href", Tuple.Create("\r\n               href=\"", 689), Tuple.Create("\"", 822)
            
            #line 27 "..\..\Views\Shared\Manage\Details.cshtml"
, Tuple.Create(Tuple.Create("", 712), Tuple.Create<System.Object, System.Int32>(Url.Controller<ManageController>().Action(c => c.Edit, Model.GetID<int>(), Request.Url?.AbsoluteUri, false)
            
            #line default
            #line hidden
, 712), false)
);

WriteLiteral(">\r\n                <glyph>&#xe065;</glyph>\r\n                Edit\r\n            </a" +
">\r\n");

            
            #line 31 "..\..\Views\Shared\Manage\Details.cshtml"
            }


            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteLiteral(" class=\"btn-default right\"");

WriteAttribute("href", Tuple.Create(" href=\"", 964), Tuple.Create("\"", 989)
            
            #line 33 "..\..\Views\Shared\Manage\Details.cshtml"
, Tuple.Create(Tuple.Create("", 971), Tuple.Create<System.Object, System.Int32>(ViewBag.ReturnURL
            
            #line default
            #line hidden
, 971), false)
);

WriteLiteral(">\r\n                <glyph>&#xe091;</glyph>\r\n                Back\r\n            </a" +
">\r\n");

            
            #line 37 "..\..\Views\Shared\Manage\Details.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <h1>\r\n");

WriteLiteral("        ");

            
            #line 40 "..\..\Views\Shared\Manage\Details.cshtml"
   Write(Model.GetFriendlyTypeName());

            
            #line default
            #line hidden
WriteLiteral(" Details\r\n    </h1>\r\n\r\n    <h2>\r\n");

WriteLiteral("        ");

            
            #line 44 "..\..\Views\Shared\Manage\Details.cshtml"
   Write(Model.ToString());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </h2>\r\n\r\n");

            
            #line 47 "..\..\Views\Shared\Manage\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\Shared\Manage\Details.cshtml"
     foreach (var Meta in Fields)
        {
        Meta.PropertyName.ToUrlSlug();

        var Field = new ViewField(ViewContext, Model.TrueModelType(), Meta.PropertyName, Model, ViewType);

        
            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\Shared\Manage\Details.cshtml"
   Write(Html.ViewField(Field));

            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\Shared\Manage\Details.cshtml"
                              
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 56 "..\..\Views\Shared\Manage\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 56 "..\..\Views\Shared\Manage\Details.cshtml"
     if (!string.IsNullOrEmpty(ViewBag.ReturnURL))
        {
        if (ViewContext.AllowEdit(Model.TrueModelType()))
            {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteLiteral(" class=\"btn-default right\"");

WriteAttribute("href", Tuple.Create(" \r\n               href=\"", 1626), Tuple.Create("\"", 1760)
            
            #line 61 "..\..\Views\Shared\Manage\Details.cshtml"
, Tuple.Create(Tuple.Create("", 1650), Tuple.Create<System.Object, System.Int32>(Url.Controller<ManageController>().Action(c => c.Edit, Model.GetID<int>(), Request.Url?.AbsoluteUri, false)
            
            #line default
            #line hidden
, 1650), false)
);

WriteLiteral("\r\n               key-bind-click=\"Ctrl+E\"");

WriteLiteral("\r\n               key-bind-click-name=\"Edit\"");

WriteLiteral(">\r\n                <glyph>&#xe065;</glyph>\r\n                Edit\r\n            </a" +
">\r\n");

            
            #line 67 "..\..\Views\Shared\Manage\Details.cshtml"
            }


            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteLiteral(" class=\"btn-default right\"");

WriteAttribute("href", Tuple.Create("\r\n               href=\"", 1985), Tuple.Create("\"", 2026)
            
            #line 70 "..\..\Views\Shared\Manage\Details.cshtml"
, Tuple.Create(Tuple.Create("", 2008), Tuple.Create<System.Object, System.Int32>(ViewBag.ReturnURL
            
            #line default
            #line hidden
, 2008), false)
);

WriteLiteral("\r\n               key-bind-click=\"Esc\"");

WriteLiteral("\r\n               key-bind-click-name=\"Back\"");

WriteLiteral(">\r\n                <glyph>&#xe091;</glyph>\r\n                Back\r\n            </a" +
">\r\n");

            
            #line 76 "..\..\Views\Shared\Manage\Details.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
