#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.Design;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Routing;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Shared\Manage\Details.cshtml"
    using LCore.Extensions;
    
    #line default
    #line hidden
    using LMVC;
    using LMVC.Account;
    using LMVC.Annotations;
    using LMVC.Context;
    using LMVC.Controllers;
    using LMVC.Extensions;
    using LMVC.Models;
    using Singularity;
    
    #line 5 "..\..\Views\Shared\Manage\Details.cshtml"
    using Singularity.Extensions;
    
    #line default
    #line hidden
    using Singularity.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Manage/Details.cshtml")]
    public partial class _Views_Shared_Manage_Details_cshtml : System.Web.Mvc.WebViewPage<IModel>
    {
        public _Views_Shared_Manage_Details_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n\r\n");

WriteLiteral("\r\n");

            
            #line 7 "..\..\Views\Shared\Manage\Details.cshtml"
  
    ViewBag.Title = "Details";

    const ControllerHelper.ViewType ViewType = ControllerHelper.ViewType.Display;

    var Groups = Model as IFieldGroups;

    IEnumerable<ModelMetadata> Fields = Groups != null ? Groups.GetFieldGroup(Context, ViewType) : FieldGroups.GetFieldGroup(Context, Model.TrueModelType(), ViewType);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"details wide-form\"");

WriteLiteral(">\r\n\r\n");

            
            #line 21 "..\..\Views\Shared\Manage\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Shared\Manage\Details.cshtml"
     if (!string.IsNullOrEmpty(ViewBag.ReturnURL))
        {
        if (ViewContext.AllowEdit(Model.TrueModelType()))
            {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteLiteral(" class=\"btn-default right\"");

WriteAttribute("href", Tuple.Create("\r\n               href=\"", 659), Tuple.Create("\"", 810)
            
            #line 26 "..\..\Views\Shared\Manage\Details.cshtml"
, Tuple.Create(Tuple.Create("", 682), Tuple.Create<System.Object, System.Int32>(Url.Controller<ManageController>().Action(Controller => Controller.Edit, Model.GetID<int>(), Request.Url?.AbsoluteUri, false)
            
            #line default
            #line hidden
, 682), false)
);

WriteLiteral(">\r\n                <glyph>&#xe065;</glyph>\r\n                Edit\r\n            </a" +
">\r\n");

            
            #line 30 "..\..\Views\Shared\Manage\Details.cshtml"
            }


            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteLiteral(" class=\"btn-default right\"");

WriteAttribute("href", Tuple.Create(" href=\"", 948), Tuple.Create("\"", 973)
            
            #line 32 "..\..\Views\Shared\Manage\Details.cshtml"
, Tuple.Create(Tuple.Create("", 955), Tuple.Create<System.Object, System.Int32>(ViewBag.ReturnURL
            
            #line default
            #line hidden
, 955), false)
);

WriteLiteral(">\r\n            <glyph>&#xe091;</glyph>\r\n            Back\r\n        </a>\r\n");

            
            #line 36 "..\..\Views\Shared\Manage\Details.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <h1>\r\n");

WriteLiteral("        ");

            
            #line 39 "..\..\Views\Shared\Manage\Details.cshtml"
   Write(Model.GetFriendlyTypeName());

            
            #line default
            #line hidden
WriteLiteral(" Details\r\n    </h1>\r\n\r\n    <h2>\r\n");

WriteLiteral("        ");

            
            #line 43 "..\..\Views\Shared\Manage\Details.cshtml"
   Write(Model.ToString());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </h2>\r\n\r\n");

            
            #line 46 "..\..\Views\Shared\Manage\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 46 "..\..\Views\Shared\Manage\Details.cshtml"
     foreach (var Meta in Fields)
        {
        Meta.PropertyName.ToUrlSlug();

        var Field = new ViewField(ViewContext, Model.TrueModelType(), Meta.PropertyName, Model, ViewType);

        
            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\Shared\Manage\Details.cshtml"
   Write(Html.ViewField(Field));

            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\Shared\Manage\Details.cshtml"
                              
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 55 "..\..\Views\Shared\Manage\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\Shared\Manage\Details.cshtml"
     if (!string.IsNullOrEmpty(ViewBag.ReturnURL))
        {
        if (ViewContext.AllowEdit(Model.TrueModelType()))
            {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteLiteral(" class=\"btn-default right\"");

WriteAttribute("href", Tuple.Create("\r\n               href=\"", 1598), Tuple.Create("\"", 1749)
            
            #line 60 "..\..\Views\Shared\Manage\Details.cshtml"
, Tuple.Create(Tuple.Create("", 1621), Tuple.Create<System.Object, System.Int32>(Url.Controller<ManageController>().Action(Controller => Controller.Edit, Model.GetID<int>(), Request.Url?.AbsoluteUri, false)
            
            #line default
            #line hidden
, 1621), false)
);

WriteLiteral("\r\n               key-bind-click=\"Ctrl+E\"");

WriteLiteral("\r\n               key-bind-click-name=\"Edit\"");

WriteLiteral(">\r\n                <glyph>&#xe065;</glyph>\r\n                Edit\r\n            </a" +
">\r\n");

            
            #line 66 "..\..\Views\Shared\Manage\Details.cshtml"
            }


            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteLiteral(" class=\"btn-default right\"");

WriteAttribute("href", Tuple.Create("\r\n           href=\"", 1970), Tuple.Create("\"", 2007)
            
            #line 69 "..\..\Views\Shared\Manage\Details.cshtml"
, Tuple.Create(Tuple.Create("", 1989), Tuple.Create<System.Object, System.Int32>(ViewBag.ReturnURL
            
            #line default
            #line hidden
, 1989), false)
);

WriteLiteral("\r\n           key-bind-click=\"Esc\"");

WriteLiteral("\r\n           key-bind-click-name=\"Back\"");

WriteLiteral(">\r\n            <glyph>&#xe091;</glyph>\r\n            Back\r\n        </a>\r\n");

            
            #line 75 "..\..\Views\Shared\Manage\Details.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
