#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.Design;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Routing;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\Manage\Exports.cshtml"
    using LCore.Extensions;
    
    #line default
    #line hidden
    using Singularity;
    using Singularity.Context;
    using Singularity.Controllers;
    
    #line 4 "..\..\Views\Shared\Manage\Exports.cshtml"
    using Singularity.Extensions;
    
    #line default
    #line hidden
    using Singularity.Models;
    
    #line 6 "..\..\Views\Shared\Manage\Exports.cshtml"
    using Singularity.Routes;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Manage/Exports.cshtml")]
    public partial class _Views_Shared_Manage_Exports_cshtml : System.Web.Mvc.WebViewPage<ManageViewModel>
    {
        public _Views_Shared_Manage_Exports_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\Shared\Manage\Exports.cshtml"
  
    string ControllerTypeName = ViewContext.Controller.GetType().FullName;

    List<CustomExport> Exports = CustomExport.Find(Context.GetModelContext(), Model.ModelType, ControllerTypeName).List();

    Dictionary<string, List<CustomExport>> ExportGroups = Exports.Group();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 18 "..\..\Views\Shared\Manage\Exports.cshtml"
 if (ViewContext.AllowExport(Model.ModelType))
    {
    CustomExport DefaultExport = null;


            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"manage-export\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" class=\"btn-info btn right method-show-hide relative\"");

WriteLiteral(" click-fade-toggle=\".manage-export-full\"");

WriteLiteral(">\r\n            <glyph");

WriteLiteral(" class=\"manage-export-full absolute\"");

WriteLiteral(">&#x2b;</glyph>\r\n            <glyph");

WriteLiteral(" class=\"manage-export-full absolute\"");

WriteLiteral(" style=\" display: none;\"");

WriteLiteral(">&#x2212;</glyph>\r\n        </span>\r\n\r\n        <h2>Exports</h2>\r\n\r\n        <div");

WriteLiteral(" class=\"manage-export-full\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 31 "..\..\Views\Shared\Manage\Exports.cshtml"
       Write(Html.TextContent($"Manage_ExportCSV_{Model.ModelType.GetFriendlyTypeName()}", "Export", ShowText: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 33 "..\..\Views\Shared\Manage\Exports.cshtml"
            
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Shared\Manage\Exports.cshtml"
             if (Exports != null && Exports.Count > 0)
                {
                foreach (var Export in Exports)
                    {
                    if (Export.Name == CustomExport.DefaultName)
                        {
                        DefaultExport = Export;
                        }
                    }

                if (DefaultExport != null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"export-row\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 47 "..\..\Views\Shared\Manage\Exports.cshtml"
                   Write(Html.ActionLink("Default Export",
                           nameof(ManageController.Export),
                           Controllers.Manage.Actions.Route_Export(Model, DefaultExport)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1890), Tuple.Create("\"", 2041)
            
            #line 50 "..\..\Views\Shared\Manage\Exports.cshtml"
, Tuple.Create(Tuple.Create("", 1897), Tuple.Create<System.Object, System.Int32>(Url.Controller<CustomExportController>().Action(Controller => Controller.Edit, DefaultExport.CustomExportID, Request.Url?.AbsoluteUri, false)
            
            #line default
            #line hidden
, 1897), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(">\r\n                                <glyph>&#xe065;</glyph>\r\n                     " +
"       </div>\r\n                        </a>\r\n                    </div>\r\n");

            
            #line 56 "..\..\Views\Shared\Manage\Exports.cshtml"
                    }
                else
                    {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"export-row\"");

WriteLiteral(">\r\n                        ");

WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 61 "..\..\Views\Shared\Manage\Exports.cshtml"
                   Write(Html.ActionLink("Default Export",
                            nameof(ManageController.Export),
                            Controllers.Manage.Actions.Route_Export(Model)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2670), Tuple.Create("\"", 3134)
            
            #line 64 "..\..\Views\Shared\Manage\Exports.cshtml"
, Tuple.Create(Tuple.Create("", 2677), Tuple.Create<System.Object, System.Int32>(Url.Controller<CustomExportController>().QS(new Dictionary<string, object> {
                                {"ExportType", Model.ModelType.FullName},
                                {"Name", CustomExport.DefaultName},
                                {"ManagementPage", ViewContext.GetManageController().GetType().FullName}
                            })
                            .Action(Controller => Controller.Create, Request.Url?.AbsoluteUri)
            
            #line default
            #line hidden
, 2677), false)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(">\r\n                                <glyph>&#xe065;</glyph>\r\n                     " +
"       </div>\r\n                        </a>\r\n                    </div>\r\n");

            
            #line 75 "..\..\Views\Shared\Manage\Exports.cshtml"
                    }
                foreach (string Group in ExportGroups.Keys)
                    {
                    bool IsGroup = !string.IsNullOrEmpty(Group);
                    if (IsGroup)
                        {

            
            #line default
            #line hidden
WriteLiteral("                        <span");

WriteLiteral(" class=\"btn-info btn right method-show-hide relative\"");

WriteAttribute("click-fade-toggle", Tuple.Create(" click-fade-toggle=\"", 3664), Tuple.Create("\"", 3726)
, Tuple.Create(Tuple.Create("", 3684), Tuple.Create(".manage-export-group-", 3684), true)
            
            #line 81 "..\..\Views\Shared\Manage\Exports.cshtml"
                                           , Tuple.Create(Tuple.Create("", 3705), Tuple.Create<System.Object, System.Int32>(Group.RemoveAll(" ")
            
            #line default
            #line hidden
, 3705), false)
);

WriteLiteral(">\r\n                            <glyph");

WriteAttribute("class", Tuple.Create(" class=\"", 3764), Tuple.Create("\"", 3822)
, Tuple.Create(Tuple.Create("", 3772), Tuple.Create("manage-export-group-", 3772), true)
            
            #line 82 "..\..\Views\Shared\Manage\Exports.cshtml"
, Tuple.Create(Tuple.Create("", 3792), Tuple.Create<System.Object, System.Int32>(Group.RemoveAll(" ")
            
            #line default
            #line hidden
, 3792), false)
, Tuple.Create(Tuple.Create(" ", 3813), Tuple.Create("absolute", 3814), true)
);

WriteLiteral(">&#x2b;</glyph>\r\n                            <glyph");

WriteAttribute("class", Tuple.Create(" class=\"", 3874), Tuple.Create("\"", 3932)
, Tuple.Create(Tuple.Create("", 3882), Tuple.Create("manage-export-group-", 3882), true)
            
            #line 83 "..\..\Views\Shared\Manage\Exports.cshtml"
, Tuple.Create(Tuple.Create("", 3902), Tuple.Create<System.Object, System.Int32>(Group.RemoveAll(" ")
            
            #line default
            #line hidden
, 3902), false)
, Tuple.Create(Tuple.Create(" ", 3923), Tuple.Create("absolute", 3924), true)
);

WriteLiteral(" style=\" display: none;\"");

WriteLiteral(">&#x2212;</glyph>\r\n                        </span>\r\n");

            
            #line 85 "..\..\Views\Shared\Manage\Exports.cshtml"


            
            #line default
            #line hidden
WriteLiteral("                        <h3>\r\n");

WriteLiteral("                            ");

            
            #line 87 "..\..\Views\Shared\Manage\Exports.cshtml"
                       Write(Group);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </h3>\r\n");

            
            #line 89 "..\..\Views\Shared\Manage\Exports.cshtml"
                        }


            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 4161), Tuple.Create("\"", 4210)
, Tuple.Create(Tuple.Create("", 4169), Tuple.Create("manage-export-group-", 4169), true)
            
            #line 91 "..\..\Views\Shared\Manage\Exports.cshtml"
, Tuple.Create(Tuple.Create("", 4189), Tuple.Create<System.Object, System.Int32>(Group.RemoveAll(" ")
            
            #line default
            #line hidden
, 4189), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 4211), Tuple.Create("\"", 4252)
            
            #line 91 "..\..\Views\Shared\Manage\Exports.cshtml"
   , Tuple.Create(Tuple.Create("", 4219), Tuple.Create<System.Object, System.Int32>(IsGroup ? "display:none;" : ""
            
            #line default
            #line hidden
, 4219), false)
);

WriteLiteral(">\r\n");

            
            #line 92 "..\..\Views\Shared\Manage\Exports.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 92 "..\..\Views\Shared\Manage\Exports.cshtml"
                         foreach (var Export in ExportGroups[Group])
                            {

            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"export-row\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 96 "..\..\Views\Shared\Manage\Exports.cshtml"
                           Write(Html.ActionLink(Export.Name,
                                        nameof(ManageController.Export),
                                        Controllers.Manage.Actions.Route_Export(Model, Export)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4763), Tuple.Create("\"", 4907)
            
            #line 99 "..\..\Views\Shared\Manage\Exports.cshtml"
, Tuple.Create(Tuple.Create("", 4770), Tuple.Create<System.Object, System.Int32>(Url.Controller<CustomExportController>().Action(Controller => Controller.Edit, Export.CustomExportID, Request.Url?.AbsoluteUri, false)
            
            #line default
            #line hidden
, 4770), false)
);

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(">\r\n                                        <glyph>&#xe065;</glyph>\r\n             " +
"                       </div>\r\n                                </a>\r\n           " +
"                 </div>\r\n");

            
            #line 105 "..\..\Views\Shared\Manage\Exports.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n");

            
            #line 107 "..\..\Views\Shared\Manage\Exports.cshtml"
                    }
                }
            else
                {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"export-row\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 113 "..\..\Views\Shared\Manage\Exports.cshtml"
               Write(Html.ActionLink("Export",
                        nameof(ManageController.Export),
                        Controllers.Manage.Actions.Route_Export(Model)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5614), Tuple.Create("\"", 6057)
            
            #line 116 "..\..\Views\Shared\Manage\Exports.cshtml"
, Tuple.Create(Tuple.Create("", 5621), Tuple.Create<System.Object, System.Int32>(Url.Controller<CustomExportController>().QS(new Dictionary<string, object>
                        {
                            {"ExportType", Model.ModelType.FullName},
                            {"Name", CustomExport.DefaultName},
                            {"ManagementPage", ViewContext.GetManageController().GetType().FullName}
                        }).Action(Controller => Controller.Create, Request.Url?.AbsoluteUri)
            
            #line default
            #line hidden
, 5621), false)
);

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(">\r\n                            <glyph>&#xe065;</glyph>\r\n                        <" +
"/div>\r\n                    </a>\r\n                </div>\r\n");

            
            #line 127 "..\..\Views\Shared\Manage\Exports.cshtml"

                }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 130 "..\..\Views\Shared\Manage\Exports.cshtml"
            
            
            #line default
            #line hidden
            
            #line 130 "..\..\Views\Shared\Manage\Exports.cshtml"
             if (ViewContext.AllowCreate(typeof(CustomExport)))
                {

            
            #line default
            #line hidden
WriteLiteral("                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 6376), Tuple.Create("\"", 6719)
            
            #line 132 "..\..\Views\Shared\Manage\Exports.cshtml"
, Tuple.Create(Tuple.Create("", 6383), Tuple.Create<System.Object, System.Int32>(Url.Controller<CustomExportController>().QS(new Dictionary<string, object>
                    {
                    {"ExportType", Model.ModelType.FullName},
                    {"ManagementPage", ViewContext.Controller.GetType().FullName}
                    }).Action(Controller => Controller.Create, Request.Url?.AbsoluteUri)
            
            #line default
            #line hidden
, 6383), false)
);

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(">\r\n                        <glyph>&#x2b;</glyph>\r\n                    </div>\r\n   " +
"             </a>\r\n");

            
            #line 141 "..\..\Views\Shared\Manage\Exports.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n");

            
            #line 144 "..\..\Views\Shared\Manage\Exports.cshtml"
    }
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
