#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.Design;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Routing;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Views\Shared\Manage\Manage.cshtml"
    using LCore.Extensions;
    
    #line default
    #line hidden
    using Singularity;
    using Singularity.Context;
    using Singularity.Controllers;
    
    #line 6 "..\..\Views\Shared\Manage\Manage.cshtml"
    using Singularity.Extensions;
    
    #line default
    #line hidden
    using Singularity.Models;
    
    #line 4 "..\..\Views\Shared\Manage\Manage.cshtml"
    using Singularity.Routes;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Manage/Manage.cshtml")]
    public partial class _Views_Shared_Manage_Manage_cshtml : System.Web.Mvc.WebViewPage<ManageViewModel>
    {
        public _Views_Shared_Manage_Manage_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\Shared\Manage\Manage.cshtml"
  
    ViewBag.Title = Model.Title;

    ViewBag.PaginationCount = 0;

    // So ManageRow can view ManageModel data
    ViewBag.ManageModel = Model;


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n");

            
            #line 21 "..\..\Views\Shared\Manage\Manage.cshtml"
 if (Html.ViewExists(PartialViews.Manage.Before))
    {
    
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Shared\Manage\Manage.cshtml"
Write(Html.Partial(PartialViews.Manage.Before, Model));

            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Shared\Manage\Manage.cshtml"
                                                    
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n<h1>\r\n");

WriteLiteral("    ");

            
            #line 27 "..\..\Views\Shared\Manage\Manage.cshtml"
Write(Html.TextContent($"Manage_Header_{Model.FriendlyModelTypeName}", Model.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n</h1>\r\n\r\n<div");

WriteAttribute("class", Tuple.Create(" class=\"", 639), Tuple.Create("\"", 685)
, Tuple.Create(Tuple.Create("", 647), Tuple.Create("manage", 647), true)
, Tuple.Create(Tuple.Create(" ", 653), Tuple.Create("manage-", 654), true)
            
            #line 30 "..\..\Views\Shared\Manage\Manage.cshtml"
, Tuple.Create(Tuple.Create("", 661), Tuple.Create<System.Object, System.Int32>(Model.ModelTypeCssClass
            
            #line default
            #line hidden
, 661), false)
);

WriteLiteral(" remember-page>\r\n\r\n\r\n");

            
            #line 33 "..\..\Views\Shared\Manage\Manage.cshtml"
    
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Shared\Manage\Manage.cshtml"
      
        var Controller = ViewContext.Controller as ManageController;
    
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 36 "..\..\Views\Shared\Manage\Manage.cshtml"
    
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Shared\Manage\Manage.cshtml"
     if (Controller != null &&
                                Controller.OverridePermissions.Create == true)
        {

            
            #line default
            #line hidden
WriteLiteral("        <div>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 944), Tuple.Create("\"", 1046)
            
            #line 40 "..\..\Views\Shared\Manage\Manage.cshtml"
, Tuple.Create(Tuple.Create("", 951), Tuple.Create<System.Object, System.Int32>(Url.Controller<ManageController>().Action(Controller.CreateAction, Request.Url?.AbsoluteUri)
            
            #line default
            #line hidden
, 951), false)
);

WriteLiteral("\r\n               key-bind-click=\"Numpad +\"");

WriteAttribute("key-bind-click-name", Tuple.Create("\r\n               key-bind-click-name=\"", 1089), Tuple.Create("\"", 1159)
, Tuple.Create(Tuple.Create("", 1127), Tuple.Create("New", 1127), true)
            
            #line 42 "..\..\Views\Shared\Manage\Manage.cshtml"
, Tuple.Create(Tuple.Create(" ", 1130), Tuple.Create<System.Object, System.Int32>(Model.FriendlyModelTypeName
            
            #line default
            #line hidden
, 1131), false)
);

WriteLiteral(">\r\n                <glyph>&#x2a;</glyph>\r\n");

WriteLiteral("                ");

            
            #line 44 "..\..\Views\Shared\Manage\Manage.cshtml"
           Write(Html.TextContent($"Manage_CreateNew_{Model.FriendlyModelTypeName}", $"New {Model.FriendlyModelTypeName}"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </a>\r\n        </div>\r\n");

            
            #line 47 "..\..\Views\Shared\Manage\Manage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 49 "..\..\Views\Shared\Manage\Manage.cshtml"
Write(Html.Partial(PartialViews.Manage.Pagination, Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 50 "..\..\Views\Shared\Manage\Manage.cshtml"
Write(Html.Partial(PartialViews.Manage.Search, Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 52 "..\..\Views\Shared\Manage\Manage.cshtml"
    
            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\Shared\Manage\Manage.cshtml"
     if (!ViewData.ModelState.IsValid)
        {

            
            #line default
            #line hidden
WriteLiteral("        <span");

WriteLiteral(" class=\"errors\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 55 "..\..\Views\Shared\Manage\Manage.cshtml"
       Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n");

            
            #line 57 "..\..\Views\Shared\Manage\Manage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <table");

WriteLiteral(" class=\"manage-table\"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("        ");

            
            #line 61 "..\..\Views\Shared\Manage\Manage.cshtml"
   Write(Html.Partial(PartialViews.Manage.HeaderRow, Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        <tbody>\r\n");

            
            #line 64 "..\..\Views\Shared\Manage\Manage.cshtml"
            
            
            #line default
            #line hidden
            
            #line 64 "..\..\Views\Shared\Manage\Manage.cshtml"
             if (Model.Models != null)
                {
                if (Model.TotalItems == 0)
                    {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td");

WriteAttribute("colspan", Tuple.Create(" colspan=\"", 1937), Tuple.Create("\"", 1985)
            
            #line 69 "..\..\Views\Shared\Manage\Manage.cshtml"
, Tuple.Create(Tuple.Create("", 1947), Tuple.Create<System.Object, System.Int32>(Model.GetVisibleColumns().Count + 3
            
            #line default
            #line hidden
, 1947), false)
);

WriteLiteral(" class=\"no-results center\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 70 "..\..\Views\Shared\Manage\Manage.cshtml"
                       Write(Html.TextContent($"Manage_NoResults_{Model.FriendlyModelTypeName}", "No results found"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                    </tr>\r\n");

            
            #line 73 "..\..\Views\Shared\Manage\Manage.cshtml"
                    }
                else
                    {
                    foreach (var Item in Model.Models)
                        {
                        if (Model.InlineEditID == Item.GetID())
                            {
                            ViewBag.InlineEdit = true;
                            ViewBag.InlineEditID = Model.InlineEditID;
                            }

                        
            
            #line default
            #line hidden
            
            #line 84 "..\..\Views\Shared\Manage\Manage.cshtml"
                   Write(Html.Partial(PartialViews.Manage.Row, Item));

            
            #line default
            #line hidden
            
            #line 84 "..\..\Views\Shared\Manage\Manage.cshtml"
                                                                    

                        if (Model.InlineEditID == Item.GetID())
                            {
                            ViewBag.InlineEdit = false;
                            ViewBag.InlineEditID = null;
                            }
                        }
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n");

            
            #line 96 "..\..\Views\Shared\Manage\Manage.cshtml"
    
            
            #line default
            #line hidden
            
            #line 96 "..\..\Views\Shared\Manage\Manage.cshtml"
      
        ViewBag.PaginationCount = 1;
    
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 99 "..\..\Views\Shared\Manage\Manage.cshtml"
Write(Html.Partial(PartialViews.Manage.Pagination, Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 101 "..\..\Views\Shared\Manage\Manage.cshtml"
    
            
            #line default
            #line hidden
            
            #line 101 "..\..\Views\Shared\Manage\Manage.cshtml"
     if (Model.ModelType.Meta().Properties.Has(m => m.PropertyName == ControllerHelper.AutomaticFields.Active) &&
                                ViewContext.AllowViewInactive(Model.ModelType))
        {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"show-hide-inactive\"");

WriteLiteral(">\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3390), Tuple.Create("\"", 3642)
            
            #line 105 "..\..\Views\Shared\Manage\Manage.cshtml"
, Tuple.Create(Tuple.Create("", 3397), Tuple.Create<System.Object, System.Int32>(Url.Controller<ManageController>()
                .QS(Controllers.Manage.Actions.Route_ToggleInactive(Model))
                .Lambda<int, string, SortDirection, string, string, ControllerHelper.ManageViewType, string, bool>(c => c.Manage)
            
            #line default
            #line hidden
, 3397), false)
);

WriteLiteral(">\r\n");

            
            #line 108 "..\..\Views\Shared\Manage\Manage.cshtml"
                
            
            #line default
            #line hidden
            
            #line 108 "..\..\Views\Shared\Manage\Manage.cshtml"
                  
                    string ShowInactiveStr = Model.ViewType.HasFlag(ControllerHelper.ManageViewType.Inactive) ? "Show Active" : "Show Inactive";
                
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("                ");

            
            #line 112 "..\..\Views\Shared\Manage\Manage.cshtml"
           Write(Html.TextContent($"Manage_{ShowInactiveStr}_{Model.ModelType.GetFriendlyTypeName()}", ShowInactiveStr));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </a>\r\n\r\n        </div>\r\n");

            
            #line 116 "..\..\Views\Shared\Manage\Manage.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 118 "..\..\Views\Shared\Manage\Manage.cshtml"
    
            
            #line default
            #line hidden
            
            #line 118 "..\..\Views\Shared\Manage\Manage.cshtml"
     if (Model.Controller.ArchiveActive)
        {
        string ShowArchiveStr = Model.ViewType.HasFlag(ControllerHelper.ManageViewType.Archive) ? "Show Archived" : "Show Current";


            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"show-hide-archive\"");

WriteLiteral(">\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4262), Tuple.Create("\"", 4513)
            
            #line 123 "..\..\Views\Shared\Manage\Manage.cshtml"
, Tuple.Create(Tuple.Create("", 4269), Tuple.Create<System.Object, System.Int32>(Url.Controller<ManageController>()
                .QS(Controllers.Manage.Actions.Route_ToggleArchive(Model))
                .Lambda<int, string, SortDirection, string, string, ControllerHelper.ManageViewType, string, bool>(c => c.Manage)
            
            #line default
            #line hidden
, 4269), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 126 "..\..\Views\Shared\Manage\Manage.cshtml"
           Write(Html.TextContent($"Manage_{ShowArchiveStr}_{Model.ModelType.GetFriendlyTypeName()}", ShowArchiveStr));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </a>\r\n        </div>\r\n");

            
            #line 129 "..\..\Views\Shared\Manage\Manage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 131 "..\..\Views\Shared\Manage\Manage.cshtml"
Write(Html.Partial(PartialViews.Manage.CustomExport, Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n</div>\r\n\r\n");

WriteLiteral("\r\n");

            
            #line 136 "..\..\Views\Shared\Manage\Manage.cshtml"
 if (Html.ViewExists(PartialViews.Manage.After))
    {
    
            
            #line default
            #line hidden
            
            #line 138 "..\..\Views\Shared\Manage\Manage.cshtml"
Write(Html.Partial(PartialViews.Manage.After, Model));

            
            #line default
            #line hidden
            
            #line 138 "..\..\Views\Shared\Manage\Manage.cshtml"
                                                   
    }
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
