#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.Design;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Routing;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using LCore.Extensions;
    using Singularity;
    using Singularity.Context;
    using Singularity.Controllers;
    
    #line 3 "..\..\Views\Shared\Manage\Pagination.cshtml"
    using Singularity.Extensions;
    
    #line default
    #line hidden
    using Singularity.Models;
    
    #line 5 "..\..\Views\Shared\Manage\Pagination.cshtml"
    using Singularity.Routes;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Manage/Pagination.cshtml")]
    public partial class _Views_Shared_Manage_Pagination_cshtml : System.Web.Mvc.WebViewPage<ManageViewModel>
    {
        public _Views_Shared_Manage_Pagination_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 9 "..\..\Views\Shared\Manage\Pagination.cshtml"
  
    ViewBag.PaginationCount = (ViewBag.PaginationCount == null ? 0 : (int)ViewBag.PaginationCount) + 1;

    int ShowingStart = Model.Page * Model.Controller.RowsPerPage + 1;
    int ShowingEnd = Model.Page * Model.Controller.RowsPerPage + Model.Controller.RowsPerPage;
    int ShowingTotal = Model.TotalItems;

    string ShowingStartStr = ShowingStart.ToString("N0");
    string ShowingEndStr = ShowingEnd.ToString("N0");
    string ShowingTotalStr = ShowingTotal.ToString("N0");

    if (ShowingEnd > ShowingTotal)
        {
        /*
                ShowingEnd = ShowingTotal;
        */
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"manage-pagination\"");

WriteLiteral(">\r\n");

            
            #line 29 "..\..\Views\Shared\Manage\Pagination.cshtml"
    
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Shared\Manage\Pagination.cshtml"
     if (Model.TotalItems > 0)
        {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"pagination-visible-items\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 32 "..\..\Views\Shared\Manage\Pagination.cshtml"
       Write(Html.TextContent($"Manage_Pagination_Results_{Model.FriendlyModelTypeName}", "Showing results [0] - [1] of [2]", new object[] { ShowingStartStr, ShowingEndStr, ShowingTotalStr }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

            
            #line 34 "..\..\Views\Shared\Manage\Pagination.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 36 "..\..\Views\Shared\Manage\Pagination.cshtml"
    
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Shared\Manage\Pagination.cshtml"
     if (Model.Page != 0)
        {

            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1191), Tuple.Create("\"", 1446)
            
            #line 38 "..\..\Views\Shared\Manage\Pagination.cshtml"
, Tuple.Create(Tuple.Create("", 1198), Tuple.Create<System.Object, System.Int32>(Url.Controller<ManageController>()
            .QS(Controllers.Manage.Actions.Route_Page(Model, 1) )
            .Lambda<int,string,SortDirection,string ,string , ControllerHelper.ManageViewType , string , bool>(Controller=> Controller.Manage)
            
            #line default
            #line hidden
, 1198), false)
);

WriteAttribute("key-bind-click", Tuple.Create("\r\n           key-bind-click=\"", 1447), Tuple.Create("\"", 1528)
            
            #line 41 "..\..\Views\Shared\Manage\Pagination.cshtml"
, Tuple.Create(Tuple.Create("", 1476), Tuple.Create<System.Object, System.Int32>(ViewBag.PaginationCount == 1 ? "Ctrl+Home" : null
            
            #line default
            #line hidden
, 1476), false)
);

WriteAttribute("key-bind-click-name", Tuple.Create("\r\n           key-bind-click-name=\"", 1529), Tuple.Create("\"", 1616)
            
            #line 42 "..\..\Views\Shared\Manage\Pagination.cshtml"
, Tuple.Create(Tuple.Create("", 1563), Tuple.Create<System.Object, System.Int32>(ViewBag.PaginationCount == 1 ? "First Page" : null
            
            #line default
            #line hidden
, 1563), false)
);

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"page-previous\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 44 "..\..\Views\Shared\Manage\Pagination.cshtml"
           Write(ManageViewModel.FirstPageText);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </span>\r\n        </a>\r\n");

            
            #line 47 "..\..\Views\Shared\Manage\Pagination.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1757), Tuple.Create("\"", 2020)
            
            #line 48 "..\..\Views\Shared\Manage\Pagination.cshtml"
, Tuple.Create(Tuple.Create("", 1764), Tuple.Create<System.Object, System.Int32>(Url.Controller<ManageController>()
            .QS(Controllers.Manage.Actions.Route_Page(Model, Model.Page))
            .Lambda<int,string,SortDirection,string ,string , ControllerHelper.ManageViewType , string , bool>(Controller=> Controller.Manage)
            
            #line default
            #line hidden
, 1764), false)
);

WriteAttribute("key-bind-click", Tuple.Create("\r\n           key-bind-click=\"", 2021), Tuple.Create("\"", 2102)
            
            #line 51 "..\..\Views\Shared\Manage\Pagination.cshtml"
, Tuple.Create(Tuple.Create("", 2050), Tuple.Create<System.Object, System.Int32>(ViewBag.PaginationCount == 1 ? "Ctrl+Left" : null
            
            #line default
            #line hidden
, 2050), false)
);

WriteAttribute("key-bind-click-name", Tuple.Create("\r\n           key-bind-click-name=\"", 2103), Tuple.Create("\"", 2193)
            
            #line 52 "..\..\Views\Shared\Manage\Pagination.cshtml"
, Tuple.Create(Tuple.Create("", 2137), Tuple.Create<System.Object, System.Int32>(ViewBag.PaginationCount == 1 ? "Previous Page" : null
            
            #line default
            #line hidden
, 2137), false)
);

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"page-previous\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 54 "..\..\Views\Shared\Manage\Pagination.cshtml"
           Write(ManageViewModel.PreviousPageText);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </span>\r\n        </a>\r\n");

            
            #line 57 "..\..\Views\Shared\Manage\Pagination.cshtml"
        }
    // ReSharper disable once ConditionIsAlwaysTrueOrFalse
    else if (ManageViewModel.AlwaysShowPaginationFirstLast)
        {

            
            #line default
            #line hidden
WriteLiteral("        <span");

WriteLiteral(" class=\"page-previous\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 62 "..\..\Views\Shared\Manage\Pagination.cshtml"
       Write(ManageViewModel.FirstPageText);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n");

            
            #line 64 "..\..\Views\Shared\Manage\Pagination.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <span");

WriteLiteral(" class=\"page-previous\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 66 "..\..\Views\Shared\Manage\Pagination.cshtml"
       Write(ManageViewModel.PreviousPageText);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n");

            
            #line 68 "..\..\Views\Shared\Manage\Pagination.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <span");

WriteLiteral(" class=\"page-numbers\"");

WriteLiteral(">\r\n");

            
            #line 71 "..\..\Views\Shared\Manage\Pagination.cshtml"
        
            
            #line default
            #line hidden
            
            #line 71 "..\..\Views\Shared\Manage\Pagination.cshtml"
         if (Model.TotalItems > 0)
            {
            for (int Index = 0; Index < Model.TotalPages; Index++)
                {
                if (Index == Model.Page)
                    {

            
            #line default
            #line hidden
WriteLiteral("                    <span");

WriteLiteral(" class=\"page-current\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 78 "..\..\Views\Shared\Manage\Pagination.cshtml"
                    Write(Index + 1);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </span>\r\n");

            
            #line 80 "..\..\Views\Shared\Manage\Pagination.cshtml"
                    }
                else if (Index >= Model.Page - ManageViewModel.ShowSurroundingPages &&
                    Index <= Model.Page + ManageViewModel.ShowSurroundingPages)
                    {

            
            #line default
            #line hidden
WriteLiteral("                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3273), Tuple.Create("\"", 3559)
            
            #line 84 "..\..\Views\Shared\Manage\Pagination.cshtml"
, Tuple.Create(Tuple.Create("", 3280), Tuple.Create<System.Object, System.Int32>(Url.Controller<ManageController>()
                        .QS(Controllers.Manage.Actions.Route_Page(Model, Index + 1))
                        .Lambda<int,string,SortDirection,string ,string , ControllerHelper.ManageViewType , string , bool>(Controller=> Controller.Manage)
            
            #line default
            #line hidden
, 3280), false)
);

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"page\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 88 "..\..\Views\Shared\Manage\Pagination.cshtml"
                        Write(Index + 1);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </span>\r\n                    </a>\r\n");

            
            #line 91 "..\..\Views\Shared\Manage\Pagination.cshtml"
                    }
                }
            }
        else
            {
            
            
            #line default
            #line hidden
            
            #line 96 "..\..\Views\Shared\Manage\Pagination.cshtml"
       Write(Html.TextContent($"Manage_Pagination_NoResults_{Model.FriendlyModelTypeName}", "No Results"));

            
            #line default
            #line hidden
            
            #line 96 "..\..\Views\Shared\Manage\Pagination.cshtml"
                                                                                                         
            }

            
            #line default
            #line hidden
WriteLiteral("    </span>\r\n\r\n");

            
            #line 100 "..\..\Views\Shared\Manage\Pagination.cshtml"
    
            
            #line default
            #line hidden
            
            #line 100 "..\..\Views\Shared\Manage\Pagination.cshtml"
     if (Model.Page + 1 != Model.TotalPages)
        {

            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3999), Tuple.Create("\"", 4274)
            
            #line 102 "..\..\Views\Shared\Manage\Pagination.cshtml"
, Tuple.Create(Tuple.Create("", 4006), Tuple.Create<System.Object, System.Int32>(Url.Controller<ManageController>()
                .QS(Controllers.Manage.Actions.Route_Page(Model, Model.Page + 2))
                .Lambda<int,string,SortDirection,string ,string , ControllerHelper.ManageViewType , string , bool>(Controller=> Controller.Manage)
            
            #line default
            #line hidden
, 4006), false)
);

WriteAttribute("key-bind-click", Tuple.Create("\r\n           key-bind-click=\"", 4275), Tuple.Create("\"", 4357)
            
            #line 105 "..\..\Views\Shared\Manage\Pagination.cshtml"
, Tuple.Create(Tuple.Create("", 4304), Tuple.Create<System.Object, System.Int32>(ViewBag.PaginationCount == 1 ? "Ctrl+Right" : null
            
            #line default
            #line hidden
, 4304), false)
);

WriteAttribute("key-bind-click-name", Tuple.Create("\r\n           key-bind-click-name=\"", 4358), Tuple.Create("\"", 4444)
            
            #line 106 "..\..\Views\Shared\Manage\Pagination.cshtml"
, Tuple.Create(Tuple.Create("", 4392), Tuple.Create<System.Object, System.Int32>(ViewBag.PaginationCount == 1 ? "Next Page" : null
            
            #line default
            #line hidden
, 4392), false)
);

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"page-next\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 108 "..\..\Views\Shared\Manage\Pagination.cshtml"
           Write(ManageViewModel.NextPageText);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </span>\r\n        </a>\r\n");

            
            #line 111 "..\..\Views\Shared\Manage\Pagination.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4580), Tuple.Create("\"", 4857)
            
            #line 112 "..\..\Views\Shared\Manage\Pagination.cshtml"
, Tuple.Create(Tuple.Create("", 4587), Tuple.Create<System.Object, System.Int32>(Url.Controller<ManageController>()
                .QS(Controllers.Manage.Actions.Route_Page(Model, Model.TotalPages))
                .Lambda<int,string,SortDirection,string ,string , ControllerHelper.ManageViewType , string , bool>(Controller=> Controller.Manage)
            
            #line default
            #line hidden
, 4587), false)
);

WriteAttribute("key-bind-click", Tuple.Create("\r\n           key-bind-click=\"", 4858), Tuple.Create("\"", 4938)
            
            #line 115 "..\..\Views\Shared\Manage\Pagination.cshtml"
, Tuple.Create(Tuple.Create("", 4887), Tuple.Create<System.Object, System.Int32>(ViewBag.PaginationCount == 1 ? "Ctrl+End" : null
            
            #line default
            #line hidden
, 4887), false)
);

WriteAttribute("key-bind-click-name", Tuple.Create("\r\n           key-bind-click-name=\"", 4939), Tuple.Create("\"", 5025)
            
            #line 116 "..\..\Views\Shared\Manage\Pagination.cshtml"
, Tuple.Create(Tuple.Create("", 4973), Tuple.Create<System.Object, System.Int32>(ViewBag.PaginationCount == 1 ? "Last Page" : null
            
            #line default
            #line hidden
, 4973), false)
);

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"page-last\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 118 "..\..\Views\Shared\Manage\Pagination.cshtml"
           Write(ManageViewModel.LastPageText);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </span>\r\n        </a>\r\n");

            
            #line 121 "..\..\Views\Shared\Manage\Pagination.cshtml"
        }
    // ReSharper disable once ConditionIsAlwaysTrueOrFalse
    else if (ManageViewModel.AlwaysShowPaginationFirstLast)
        {

            
            #line default
            #line hidden
WriteLiteral("        <span");

WriteLiteral(" class=\"page-next\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 126 "..\..\Views\Shared\Manage\Pagination.cshtml"
       Write(ManageViewModel.NextPageText);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n");

            
            #line 128 "..\..\Views\Shared\Manage\Pagination.cshtml"


            
            #line default
            #line hidden
WriteLiteral("        <span");

WriteLiteral(" class=\"page-last\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 130 "..\..\Views\Shared\Manage\Pagination.cshtml"
       Write(ManageViewModel.LastPageText);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n");

            
            #line 132 "..\..\Views\Shared\Manage\Pagination.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
