#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.Design;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Mvc.Routing;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Shared\Manage\Search.cshtml"
    using LCore.Extensions;
    
    #line default
    #line hidden
    using LMVC;
    using LMVC.Account;
    using LMVC.Annotations;
    using LMVC.Context;
    using LMVC.Controllers;
    using LMVC.Extensions;
    using LMVC.Models;
    
    #line 7 "..\..\Views\Shared\Manage\Search.cshtml"
    using LMVC.Routes;
    
    #line default
    #line hidden
    using Singularity;
    
    #line 5 "..\..\Views\Shared\Manage\Search.cshtml"
    using Singularity.Extensions;
    
    #line default
    #line hidden
    using Singularity.Models;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Manage/Search.cshtml")]
    public partial class _Views_Shared_Manage_Search_cshtml : System.Web.Mvc.WebViewPage<ManageViewModel>
    {
        public _Views_Shared_Manage_Search_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n\r\n");

WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\Shared\Manage\Search.cshtml"
  
    string ControllerTypeName = ViewContext.Controller.GetType().FullName;

    List<SavedSearch> SavedSearches = SavedSearch.Find(Context, Model.ModelType.FullName, ControllerTypeName).List();

    Dictionary<string, List<SavedSearch>> SavedSearchGroups = SavedSearches.Group();

    bool SearchEmpty = Model.FieldSearchTerms.Keys.Count == 0 && string.IsNullOrEmpty(Model.GlobalSearchTerm);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<div");

WriteLiteral(" class=\"manage-global-search\"");

WriteLiteral(">\r\n");

            
            #line 23 "..\..\Views\Shared\Manage\Search.cshtml"
    
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Shared\Manage\Search.cshtml"
     if (Model.FieldSearchTerms.Keys.Count > 0)
        {
        foreach (var Value in Model.FieldSearchTerms.Values)
            {
            if (Value.Operator == Expression.Equal || Value.OperatorStr == "~")
                {
                string Column = Value.Property.ToUrlSlug();


            
            #line default
            #line hidden
WriteLiteral("                <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n                    $().ready(function () {\r\n                        $(\'.manag" +
"e-");

            
            #line 33 "..\..\Views\Shared\Manage\Search.cshtml"
                              Write(Model.ModelTypeCssClass);

            
            #line default
            #line hidden
WriteLiteral(" .manage-table tbody td.");

            
            #line 33 "..\..\Views\Shared\Manage\Search.cshtml"
                                                                              Write(Column);

            
            #line default
            #line hidden
WriteLiteral(" span\').each(function () {\r\n                            const html = $(this).html" +
"();\r\n                            $(this).html(html.replace(new RegExp(`(${(\'");

            
            #line 35 "..\..\Views\Shared\Manage\Search.cshtml"
                                                                  Write(Value.Search);

            
            #line default
            #line hidden
WriteLiteral("\').escapeRegExp()})`, \'ig\'), \'<strong>$1</strong>\'));\r\n                        })" +
";\r\n                    });\r\n                </script>\r\n");

            
            #line 39 "..\..\Views\Shared\Manage\Search.cshtml"
                }
            }
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 43 "..\..\Views\Shared\Manage\Search.cshtml"
    
            
            #line default
            #line hidden
            
            #line 43 "..\..\Views\Shared\Manage\Search.cshtml"
     if (!string.IsNullOrEmpty(Model.GlobalSearchTerm))
        {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n            $().ready(function () {\r\n                $(\'.manage-");

            
            #line 47 "..\..\Views\Shared\Manage\Search.cshtml"
                      Write(Model.ModelTypeCssClass);

            
            #line default
            #line hidden
WriteLiteral(" .manage-table tbody td span\').each(function () {\r\n                    const html" +
" = $(this).html();\r\n                    $(this).html(html.replace(new RegExp(`($" +
"{(\'");

            
            #line 49 "..\..\Views\Shared\Manage\Search.cshtml"
                                                          Write(Model.GlobalSearchTerm);

            
            #line default
            #line hidden
WriteLiteral("\').escapeRegExp()})`, \'ig\'), \'<strong>$1</strong>\'));\r\n                });\r\n     " +
"       });\r\n        </script>\r\n");

            
            #line 53 "..\..\Views\Shared\Manage\Search.cshtml"
        }
    else
        {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n            $().ready(function () {\r\n                $(\'#GlobalSearchTerm\').va" +
"l(\'\');\r\n            });\r\n        </script>\r\n");

            
            #line 61 "..\..\Views\Shared\Manage\Search.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 63 "..\..\Views\Shared\Manage\Search.cshtml"
    
            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\Shared\Manage\Search.cshtml"
     if (!SearchEmpty)
        {
        using (Html.BeginForm(nameof(ManageController.Manage),
            Model.Controller.Name,
            Controllers.Manage.Actions.Route_ClearSearch(Model),
            FormMethod.Get,
            new { @class = "clear-form" }))
            {

            
            #line default
            #line hidden
WriteLiteral("            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Clear\"");

WriteLiteral(" />\r\n");

            
            #line 72 "..\..\Views\Shared\Manage\Search.cshtml"
            }
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 75 "..\..\Views\Shared\Manage\Search.cshtml"
    
            
            #line default
            #line hidden
            
            #line 75 "..\..\Views\Shared\Manage\Search.cshtml"
     if (Model.FieldSearchTerms != null &&
                    Model.FieldSearchTerms.Keys.Count > 0)
        {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n            $().ready(function () {\r\n                $(\'.filter-area span[sear" +
"ch-text]\').click(function () {\r\n                    $(\'#GlobalSearchTerm\').val($" +
"(this).attr(\'search-text\'));\r\n                });\r\n            });\r\n        </sc" +
"ript>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"filter-area\"");

WriteLiteral(">\r\n");

            
            #line 86 "..\..\Views\Shared\Manage\Search.cshtml"
            
            
            #line default
            #line hidden
            
            #line 86 "..\..\Views\Shared\Manage\Search.cshtml"
             foreach (var Value in Model.FieldSearchTerms.Values)
                {

            
            #line default
            #line hidden
WriteLiteral("                <span>\r\n                    <span");

WriteAttribute("search-text", Tuple.Create(" search-text=\"", 3117), Tuple.Create("\"", 3183)
            
            #line 89 "..\..\Views\Shared\Manage\Search.cshtml"
, Tuple.Create(Tuple.Create("", 3131), Tuple.Create<System.Object, System.Int32>(Value.Property + Value.OperatorStr + Value.Search
            
            #line default
            #line hidden
, 3131), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 90 "..\..\Views\Shared\Manage\Search.cshtml"
                   Write(Value.Property);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 91 "..\..\Views\Shared\Manage\Search.cshtml"
                   Write(Value.OperatorStr);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 92 "..\..\Views\Shared\Manage\Search.cshtml"
                   Write(Value.Search);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </span>\r\n");

WriteLiteral("                    ");

            
            #line 94 "..\..\Views\Shared\Manage\Search.cshtml"
               Write(Html.ActionLink("X", nameof(ManageController.Manage),
                        Model.Controller.Name,
                        Controllers.Manage.Actions.Route_RemoveFilter(Model, Value.Property), new { }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </span>\r\n");

            
            #line 98 "..\..\Views\Shared\Manage\Search.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n");

            
            #line 100 "..\..\Views\Shared\Manage\Search.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $().ready(function () {\r\n            const availableTags = [\r\n");

WriteLiteral("                ");

            
            #line 105 "..\..\Views\Shared\Manage\Search.cshtml"
           Write(Html.Raw(Model.GetSearchSuggestions()));

            
            #line default
            #line hidden
WriteLiteral(@"
            ];
            $(""#GlobalSearchTerm"").bind(""keydown"", function (event) {
                if (event.keyCode === $.ui.keyCode.TAB &&
                    $(this).autocomplete(""instance"").menu.active) {
                    event.preventDefault();
                }
            }).autocomplete({
                source: availableTags
            });
        });
    </script>

");

            
            #line 118 "..\..\Views\Shared\Manage\Search.cshtml"
    
            
            #line default
            #line hidden
            
            #line 118 "..\..\Views\Shared\Manage\Search.cshtml"
     if (!SearchEmpty &&
                ViewContext.AllowCreate(typeof(SavedSearch)) &&
                ViewContext.GetManageController().ViewSavedSearches)
        {

            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4383), Tuple.Create("\"", 4604)
            
            #line 122 "..\..\Views\Shared\Manage\Search.cshtml"
, Tuple.Create(Tuple.Create("", 4390), Tuple.Create<System.Object, System.Int32>(Url.Controller<SavedSearchController>()
                    .QS(Controllers.SavedSearch.Actions.Route_CreateSavedSearch(Model, ViewContext))
                    .Lambda<string>(Controller => Controller.Create)
            
            #line default
            #line hidden
, 4390), false)
);

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" title=\"Save Search\"");

WriteLiteral(">\r\n                <glyph>&#xe172;</glyph>\r\n            </div>\r\n        </a>\r\n");

            
            #line 129 "..\..\Views\Shared\Manage\Search.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 131 "..\..\Views\Shared\Manage\Search.cshtml"
    
            
            #line default
            #line hidden
            
            #line 131 "..\..\Views\Shared\Manage\Search.cshtml"
     if (SavedSearches.Count > 0 &&
                ViewContext.GetManageController().ViewSavedSearches)
        {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"manage-saved-searches\"");

WriteLiteral(">\r\n            <h2>Searches</h2>\r\n\r\n            <span");

WriteLiteral(" class=\"btn-info btn right method-show-hide relative\"");

WriteLiteral(" click-fade-toggle=\".manage-saved-searches-full\"");

WriteLiteral(">\r\n                <glyph");

WriteLiteral(" class=\"manage-saved-searches-full absolute\"");

WriteLiteral(">&#x2b;</glyph>\r\n                <glyph");

WriteLiteral(" class=\"manage-saved-searches-full absolute\"");

WriteLiteral(" style=\" display: none;\"");

WriteLiteral(">&#x2212;</glyph>\r\n            </span>\r\n\r\n            <div");

WriteLiteral(" class=\"manage-saved-searches-full\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n");

            
            #line 143 "..\..\Views\Shared\Manage\Search.cshtml"
                
            
            #line default
            #line hidden
            
            #line 143 "..\..\Views\Shared\Manage\Search.cshtml"
                 foreach (string GroupName in SavedSearchGroups.Keys)
                    {
                    List<SavedSearch> Group = SavedSearchGroups[GroupName];


            
            #line default
            #line hidden
WriteLiteral("                    <h3>");

            
            #line 147 "..\..\Views\Shared\Manage\Search.cshtml"
                   Write(GroupName);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n");

            
            #line 148 "..\..\Views\Shared\Manage\Search.cshtml"

                    foreach (var Search in Group)
                        {

            
            #line default
            #line hidden
WriteLiteral("                        <div");

WriteLiteral(" class=\"manage-saved-search\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" class=\"saved-search btn btn-default\"");

WriteAttribute("href", Tuple.Create("\r\n                               href=\"", 5786), Tuple.Create("\"", 6133)
            
            #line 153 "..\..\Views\Shared\Manage\Search.cshtml"
, Tuple.Create(Tuple.Create("", 5825), Tuple.Create<System.Object, System.Int32>(Url.Controller<ManageController>()
                                .QS(Controllers.SavedSearch.Actions.Route_ViewSavedSearch(Model, Search))
                                .Lambda<int,string,SortDirection,string ,string , ControllerHelper.ManageViewType , string , bool>(Controller=> Controller.Manage)
            
            #line default
            #line hidden
, 5825), false)
);

WriteLiteral(">\r\n                                <glyph>&#xe003;</glyph>\r\n                     " +
"           <h4>");

            
            #line 157 "..\..\Views\Shared\Manage\Search.cshtml"
                               Write(Search.Name);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                            </a>\r\n");

            
            #line 159 "..\..\Views\Shared\Manage\Search.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 159 "..\..\Views\Shared\Manage\Search.cshtml"
                             if (Model.ModelType.HasInterface<IEmailable>() &&
                            ViewContext.AllowCreate(typeof(EmailJob)))
                                {

            
            #line default
            #line hidden
WriteLiteral("                                <a");

WriteLiteral(" class=\"email-saved-search btn btn-default\"");

WriteAttribute("href", Tuple.Create("\r\n                                   href=\"", 6547), Tuple.Create("\"", 6856)
            
            #line 163 "..\..\Views\Shared\Manage\Search.cshtml"
, Tuple.Create(Tuple.Create("", 6590), Tuple.Create<System.Object, System.Int32>(Url.Controller<EmailJobController>()
                                       .QS(new Dictionary<string, object> { {"SavedSearchID", Search.SavedSearchID} })
                                       .Action(Controller => Controller.Create, Request.Url?.AbsoluteUri)
            
            #line default
            #line hidden
, 6590), false)
);

WriteLiteral(">\r\n                                    <glyph>&#x2709;</glyph>\r\n                 " +
"               </a>\r\n");

            
            #line 168 "..\..\Views\Shared\Manage\Search.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            <a");

WriteLiteral(" class=\"edit-saved-search btn btn-default\"");

WriteAttribute("href", Tuple.Create("\r\n                               href=\"", 7066), Tuple.Create("\"", 7339)
            
            #line 170 "..\..\Views\Shared\Manage\Search.cshtml"
, Tuple.Create(Tuple.Create("", 7105), Tuple.Create<System.Object, System.Int32>(Url.Controller<SavedSearchController>()
                                    .QS(Controllers.Manage.Actions.Route_Edit(Search, Request))
                                    .Lambda<int, string, bool>(Controller => Controller.Edit)
            
            #line default
            #line hidden
, 7105), false)
);

WriteLiteral(">\r\n                                <glyph>&#xe065;</glyph>\r\n                     " +
"       </a>\r\n                        </div>\r\n");

            
            #line 176 "..\..\Views\Shared\Manage\Search.cshtml"
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n");

            
            #line 180 "..\..\Views\Shared\Manage\Search.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 182 "..\..\Views\Shared\Manage\Search.cshtml"
    
            
            #line default
            #line hidden
            
            #line 182 "..\..\Views\Shared\Manage\Search.cshtml"
     using (Html.BeginForm(nameof(ManageController.Search),
                Model.Controller.Name,
                Controllers.Manage.Actions.Route_Search(Model),
                FormMethod.Post, new { id = "SearchForm" }))
        {

        
            
            #line default
            #line hidden
            
            #line 188 "..\..\Views\Shared\Manage\Search.cshtml"
   Write(Html.TextBox("GlobalSearchTerm", Model.GlobalSearchTerm));

            
            #line default
            #line hidden
            
            #line 188 "..\..\Views\Shared\Manage\Search.cshtml"
                                                                 
        
            
            #line default
            #line hidden
            
            #line 189 "..\..\Views\Shared\Manage\Search.cshtml"
   Write(Html.Hidden("FieldSearchTerms", Model.GetGlobalSearchCombined()));

            
            #line default
            #line hidden
            
            #line 189 "..\..\Views\Shared\Manage\Search.cshtml"
                                                                         


            
            #line default
            #line hidden
WriteLiteral("        <a");

WriteLiteral(" onclick=\"$(\'#SearchForm\').submit();\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(">\r\n            <glyph>&#xe003;</glyph>\r\n            <span>\r\n                Searc" +
"h\r\n            </span>\r\n        </a>\r\n");

            
            #line 197 "..\..\Views\Shared\Manage\Search.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>");

        }
    }
}
#pragma warning restore 1591
